== Preface.

To render lines harmonious to every ear, is hardly possible;
yet since no part of history is more instructive and pleasing than the lives of good men;
though the present treatise may not entertain the reader with a great variety,
it is hoped it will afford some things acceptable, which deserve imitation,
and may be a means to persuade him to religion and virtue.
Such memorials are fit to be delivered to posterity as carry
with them evident tokens of the Divine goodness and protection;
yet not to procure glory to man, to set up his wisdom, or natural or acquired parts,
but to exalt the Lord Jesus Christ alone.
Time here is short, in comparison with eternity; it glides away apace:
and possibly it may not be long ere thy forehead, reader, begin to wrinkle,
and thy hair change grey, thy eyes become dim, and knees tremble,
and thou perhaps to all enjoyments here, be as though thou hadst never been.
As the following passages of the life of my beloved uncle came chiefly from himself,
as to what relates to the first breaking forth of the blessed truth in this city;
and much of the latter part of his time was within the compass of my own knowledge,
(we having lived together above forty-two years,) I shall set them forth
in that plainness which in those early times attended the Lord`'s servants.

This our dear friend was preserved through all the
powers and governments which were in his time,
keeping in the self-denial, bearing the cross of our only Mediator and blessed Redeemer,
the Lord Jesus Christ; by which he became crucified to the world and its glory;
not valuing the lofty yet empty titles of men, high and great in the world,
so as to be dismayed or hindered thereby from approaching any in authority.
With great humility, in the love of God,
he attended them when the Lord`'s servants were under sufferings,
in order to get the oppressed eased, and the imprisoned set at liberty.
By perusing his life, thou wilt find how indefatigable he was,
yet walking inoffensively both to Jew and Gentile, and the church of God.
I conclude with desires both for myself, and all those who are quickened in the Lord,
that we may persevere in the way wherein this servant walked,
and not be like those mentioned in Judges,
who arose after the death of Joshua and the elders, and "`knew not the Lord,
nor yet the works which he had done for Israel.`"

Wherefore, reader, my desire is, that we who remain may follow the Lord faithfully;
and that he may raise in us the same zeal, diligence and valour,
as he did in this our ancient Friend,
and the rest of the elders that received the truth in the morning of the day of the Lord,
is the sincere breathing of thy friend,

[.signed-section-signature]
Richard Hawkins.
