== Testimonies

=== The Testimony of George Whitehead, concerning Gilbert Latey.

This our ancient Friend and brother learned obedience through the cross of Christ,
and by His grace approved himself faithful in his place and station,
being made a living and useful member in His church,
and well approved in his testimony and service in his day.
He was constant in his love to his brethren; and hated hypocrisy and dissimulation,
divisions and causing of schisms.
He was for many years my true companion in laborious
solicitations in the reigns of the late three kings,
viz., Charles II., James II., and William III.;
be before whom we divers times appeared in be half of our suffering Friends.
Our dear friend was much given up in that service,
and we were often comforted together in the Lord`'s presence with us,
prevailing to tender their hearts towards Friends;
though we obtained relief from King Charles II. not always, but in some particular cases,
through diligent licitation early and late.
We suffered great persecution in his reign; and he left our Friends under sufferings,
about one thousand five hundred being in prisons,
and many hundreds of families under severe prosecutions
upon the old laws made against popish recusants,
for twenty pounds a month and two thirds of their estates
for not going to the parish churches (so called),
and great spoil made upon many therefor.
The informers swarming about our religious meetings
also caused great spoil upon Friends`' goods;
whose cases were made known to King James.
In several applications, and much labour and solicitation,
we obtained the release of many prisoners,
the prevention of the writs for the seizure of Friends`' estates,
and stopping the informers.
In this service our Friend Gilbert Latey was frequent
in solicitation with me in true faith and love;
and the Lord was with us, and his hand was upon us, and he heard our prayers.
Gilbert Latey was a sensible man, of a good judgment;
and when the Lord opened to me any petition,
or proposal to make to any of these three kings, respectively,
I first imparted the same to him, and he would be presently sensible thereof,
and given up to assist in solicitation to king or parliament, or any of the nobility.

In King William`'s reign, who manifested great kindness and compassion towards us,
other Friends were stirred up in and about this city
to assist in soliciting for our religious liberty,
and also from the imposition of oaths,
wherein Gilbert Latey was truly industrious and assisting;
and also ready to help us in attending the government in Friends`' behalf,
so long as he could, until by his age and weakness he was disabled.
It would be too voluminous to repeat all our labours and exercises of this kind,
wherein we travelled together under many burdens in great humility;
wherein the Lord helped us, and many received ease and benefit thereby,
who knew little of the same, or of our exercises for them,
especially when we had occasion to approach the presence of King Charles and King James;
wherein the Lord made way for us, and gave us faith and special assistance;
blessed be his worthy name forever!

As the Lord endued him with a good degree of faith and a sense of his Spirit,
to enable him in his service and testimony for his blessed truth,
he kept the faith in sincerity and true love, wherein he ended his days in peace;
and for the ease and liberty we do now enjoy, and the merciful Providence we are under,
we have great cause to ascribe praise, honour, glory, and dominion to our God,
and to the Lamb on the throne, forever and ever.

George Whitehead

London, the 30th of 3rd mo.
1707.

=== The Testimony of Richard Hawkins, concerning his dear and well-beloved uncle, Gilbert Latey.

The testimony I have to bear concerning my deceased dear uncle is,
that he was a man fearing God and hating iniquity;
fervent and zealous against deceit and hypocrisy, and endued with a Gospel testimony;
which according to his ability he bore faithfully in his day; and the Lord was with him.
He always had a very honourable regard for those who were his elders in the Lord,
and a sincere love towards such as the Lord had raised up more lately in the ministry,
as they kept to that power which first brake forth in their
elders in the morning of this day of the Lord.
He rejoiced in such, and would often say, they were as marrow to his bones,
and his love to them was as firm and as true, as that of David and Jonathan,
in which he was still ready to lend a hand of help to those that were young or weak,
having also a true regard for the hindermost of the flock,
and would often strengthen and advise them.
Those in whom innocency and truth had place,
he encouraged to persist in the way of the Lord,
having a godly care upon him for the tender and simple-hearted;
and thus he loved the flock of the Lord`'s pasture, and was well beloved among them.
His parts were quick, and his apprehension lively; his memory good,
and his judgment sound and strong; his example shining in self-denial;
yet he was of a generous and free spirit; an early plant in the Lord`'s vineyard,
which grew and prospered to the praise and glory of God`'s grace,
who made him acceptable in and through his beloved Son, Christ Jesus, the true light,
and by the effectual operation of his power, whereby he was made serviceable to many,
and a good savour to them that walk in the way of the Lord,
and also to many that were rich, high, and great in the world.
And I am well assured the Lord hath crowned the labours of this faithful witness,
whose days in good old age ended in peace; and he hath his crown that fadeth not away,
an inheritance everlasting among the righteous in glory,
in the kingdom of our blessed Lord.
He was continued in the enjoyment of his sense and reason to the last moment of his life,
and died in the Lord, and rests from his labours, whose works follow him,
and his memorial is blessed among the righteous in the Lord`'s heritage,
he having been a worthy soldier and follower of the Lamb,
and kept his habitation in Christ Jesus.
I pray God, that both I, and all that remain, may in life and conversation,
as he hath done, bear a faithful testimony for the blessed truth,
and in the same be preserved,
to walk in the footsteps of the Christian flock to the end of our days,
having the loins of our minds girded up, and our eye single to the Lord,
and to the recompense he hath in store for the righteous,
which will remain and stand us in stead,
when we shall be called out of this fading perishing world.

Richard Hawkins.

=== A Testimony concerning my dear and well beloved husband, Gilbert Latey.

I can truly say he was a man given up to serve God and his people,
never sparing himself to do what good he could for all,
but especially for the imprisoned,
who were under suffering for their testimony to the Lord, and a good conscience.
Those who were thus exercised were always near to him,
and having both an open hand and heart to them, it was his delight to do good to all;
but in a more especial manner to the household of faith.
He was a man desirous of love and unity among the Lord`'s people,
being for healing of breaches, and informing the judgments and misunderstandings of some,
and strengthening and advising others that were weak and fainting in their minds;
by which means he was often instrumental for peace, and putting an end to differences.
He loved peace, and yet flinched not, but was given up in perilous times of suffering;
a constant testimony-bearer to the way of the Lord and to his power,
which was felt to attend his people in their meetings;
even when they were kept without doors a considerable time in the wet and cold,
where he often stood with the Lord`'s servants,
"`being made a gazing stock both by reproaches and afflictions, etc.`"
In all which I never did persuade or dared desire him either to go to this meeting,
or not to go to that,
but always left him to his freedom to go where the Lord did order him,
in which I had and still have great peace,
and I am well satisfied he hath a good reward.

He was to me a faithful loving husband, and a dear and tender father to his children,
often admonishing, advising, and instructing them to lowliness, humility,
and the fear of the Lord.
He was a good example to them,
being often concerned in the fear of the Lord to excite them to love God,
his truth and people;
by which they would feel the power of the Most High to preserve them out of evil,
as he could truly say it had done for him, and preserved him to a good old age.
Toward his latter time he delighted to be retired out of business;
and being pretty much out of the city,
and not having that frequent opportunity of delivering his mind to his children,
and his concern for their welfare in the truth continuing,
while he had strength he would write to them.
Having thus persevered, he would often say both to me and others,
that he had done the work of his day faithfully, and was sat down in the will of God,
and felt His peace to abound in him.
He often mentioned that he waited the Lord`'s call and time of being removed,
and that there was no cloud in his way, for the Lord was good to him.

The night before he departed, he gave good counsel to them that were in the room,
to fear the Lord, and not do evil for evil, but to do good for evil,
for that there was no overcoming of evil but in and by that which was good,
for in so doing,
coals of fire would be heaped on their heads exhorting very much to love and tenderness,
for the Lord would bless such as were found therein.
He was much opened in exhortation and counsel at this time,
and uttered his words with great vigour, as if he ailed little and were in a meeting.
Next day he kept his chamber, being weak of body,
but preserved in the enjoyment of his reason to the last moment;
and a very few hours before his departure, spoke to some that were about him,
"`That there was no condemnation to them that were in Christ Jesus; for, said he.
He is the lifter up of my head.
He is my strength and great salvation;`" with more to the like effect.
I might add much, but must come to a conclusion;
and therefore shall satisfy myself to say,
that I believe no woman hath parted with a better husband,
nor children with a more tender father, or sincerer man:
it is the Lord`'s will to remove him, and in that I endeavour and desire to be content.

Mary Latey

THE END.
