== The Life of Gilbert Latey.

Gilbert Latey was born of honest parents, in the county of Cornwall,
in the parish called St. Issey, in the month called February, in the year 1626.
He was the youngest child of his father, who was a yeoman, and dealt in cattle,
and kept malting, and a house of entertainment both for travellers and others.
His mother was of the best family then in the parish; her maiden name was Hocking,
a gentlewoman whose brother married Attorney-General Noy`'s sister.
Gilbert having three brothers who were abroad and did very well,
was desirous to go to some trade; and being a very likely lad, a person,
by trade a tailor, had a desire to have him for his apprentice;
and his father and master having agreed on the terms, he was bound accordingly,
and faithfully served his apprenticeship,
notwithstanding he had a very wicked and severe master.

Being desirous to improve himself in his business, he went to Plymouth,
a sea-port town in the west of England,
where he was employed by one of the chief of that trade, who was a great professor,
and afterwards mayor of the place.
He would gladly have had him continue longer with him, and promised him,
for his encouragement, the best wages that were given to any man in the town;
but in those days he had a fear towards, and a desire after the Lord,
and saw the emptiness of his master`'s profession.
He not being of a good life and conduct, Gilbert was uneasy and resolved to go to London;
and accordingly, about the month called November, in the year 1648, went there.
He was of a sober life and conduct, and having breathings in his heart after the Lord,
followed those who were of the best repute,
and esteemed to be the most zealous pastors and preachers in that time,
often hearing four sermons in a day, and being frequent in private prayer.
The Lord beholding the integrity of his heart, prospered him in such a manner,
that he grew into great reputation in the world; having much business in his trade,
and being employed and respected by persons of the first rank in the kingdom.
But, through all these outward enjoyments,
his desires were still to find peace with the Lord;
and in this seeking condition he went to hear those who seemed the most refined,
and from one of them to the other, seeking the living among the dead,
yet among them all he could not find his soul`'s beloved;
they proving to him only as the watchmen of the night.
While thus breathing, and seeking after the truth,
it was made known to him about the year 1654,
that some men who were come out of the north,
were to have a meeting at the house of Sarah Matthews, a widow,
who lived in Whitecross-street.
He repaired there,
and having heard the truth declared by that eminent minister of our Lord Jesus Christ,
Edward Burrough, was so reached by the power of the Lord, that he was convinced;
and being directed to the light of Christ in himself,
and not consulting with flesh and blood, he gave up to the leadings of the Holy Spirit,
greatly rejoicing that he had found his soul`'s beloved, and resolving,
through the Lord`'s assistance, to take up his cross and despise the shame,
accounting all things but as dross that he might win Christ.

There being few now left who came so early into the vineyard of the Lord, he was willing,
as near as he could remember, to give some account to the present and succeeding age,
how the truth prevailed, and also the names of the ministering Friends,
who in those early days first visited this city, and parts adjacent,
and were made instruments in the Lord`'s hand for turning many from darkness to light.
Though they are now all gone to their rest, their faithfulness to the Lord,
and great labours, are still fresh in memory,
and the jeopardies and sufferings they passed through, in their obedience to the Lord,
cannot be forgotten by such as were eye-witnesses.
The Lord`'s power, being still the same, has plentifully raised up more witnesses,
bearing a faithful testimony to the same truth and
power of God that the ancients came forth in;
and the Lord`'s work prospers.

The first who brought the glad tidings to this city were, Francis Howgill,
Edward Burrough, Thomas Aldam, George Fox, Richard Hubberthorn, John Audland,
Ambrose Rigge, James Nayler, and others; by whom many were turned to the Lord;
and by his everlasting power their hearts were opened
to receive his messengers into their houses,
and to offer up the same, to have meetings therein for the service of the Lord.
Among these was Simon Dring, who then lived in Watling-street,
but some time after removed into Moorfields,
where he continued to have a meeting in his house
on the first-day`'s of the week in the afternoon.

About this time also, as before related, Sarah Matthews, a widow, in Whitecross-street,
had a meeting at her house,
which was continued on the first-days in the morning for some time.
Another meeting was at Humphrey Bates`'s house, at the sign of the Snail, in Towerstreet;
another at Samuel Vasse`'s, at the Helmet in Basinghall-street;
another at Glaziers`' Hall in Thames-street, where Gerard Roberts was convinced,
and gave way to have a meeting at his house,
which was in the street called Thomas-Apostle`'s;
where ministering Friends generally met till the year 1666.

Another meeting was at William Woodcock`'s house, who lived in the Strand,
between the great gate of Somerset-house and the watergate belonging thereto.
There were several other meetings in the suburbs, and in Southwark;
at William Shewen`'s in Bermondsey-street; Daniel Flemming`'s in Blackman-street;
Henry Clark`'s on the Bank-side; and at Worcester-house in the Strand.
The work of the Lord prospering, many were convinced and made help-mates in the Gospel;
among whom Anne Downer came forth in a public testimony.
She was afterwards the wife of our honourable Friend George Whitehead;
who at this time also had a public testimony to bear for the Lord,
but had his service in other parts;
so that he came not to this city till about the year 1656.
About the time of Anne Downer`'s thus coming forth, Ruth Brown received the truth,
and was afterwards married to our Friend William Crouch; who are both still living.
The Lord raised up his servants, Sarah Blackbury, Ann Gould, and Elizabeth Peacock,
who came forth in public testimony for the Lord, his name and truth.
It being now about the year 1655,
Friends found a concern upon them to have some settled meetings,
for the sake of those who yet sat in darkness,
that they might come and hear the truth declared,
and be turned to the Lord whereupon a meeting was settled,
and the place is still continued for a meeting,
being known by the name of the meeting at Sarah Sawyer`'s. The next public meeting
was about the same year settled at the Bull and Mouth in Martin`'s-le-Grand,
near Aldersgate, which is still continued.
There were also about this time several other meetings
at Friends`' houses one at the widow Webb`'s,
in Jacob-street in Southwark,
which growing large was removed to a public meeting-house provided at Horsleydown,
and is still continued; and another in Spitalfields, which was removed,
and a public place opened for a meeting in Wheeler-street,
which has also continued there ever since; and soon after, another at Stepney,
near Mile-end, which grew large, and was afterwards removed,
and a new meeting-house built at Ratcliff,
and is continued in the same place to this day.
Another meeting also was settled at the sign of the Peel, near Hicks`'s-hall,
which is likewise continued in the same place.

Gilbert, being one among the first fruits to the Lord in this groat city,
and through the light of Christ, furnished with a quick discerning, and sound judgment,
was made serviceable in settling the church in Discipline and good order,
and long continued a pillar in the house of our God, retaining his integrity to the last.
Truth having gained upon many in several parts of the city, suburbs,
and country adjacent, they offered up themselves and their houses for its sake,
in these times of hardship and trial, among whom were those worthy servants of the Lord,
John Fielder, and Ann his wife, who were convinced at Kingston-upon-Thames;
and as faithful followers of the Lamb,
not only received the Lord`'s ministers who laboured in his work and service,
but also gave up their house for a meeting-place;
and accordingly a meeting was there settled.
Oliver Cromwell, then called Protector, residing much at Hampton-court,
this meeting became of great service,
and many were there convinced and turned to the Lord, and directed to wait in silence,
for the arising of the pure gift in themselves.
Several who then belonged to Oliver`'s household, were also convinced at this meeting,
and continued faithful; of whom there are some yet (in 1706) alive.

About the year 1658 there were several other meetings in parts about the city,
as one at Mitcham for some time, where Friends suffered much;
another in like manner at Croydon, another at Walworth, another also at Lambeth-marsh,
another at Thomas Hackleton`'s, at the Bankside, near the Falcon;
another at the Bankside, near Southwark, at Henry Clark`'s;
these being all in the county of Surrey.
The Lord`'s work prospered, who according to the prophecy of the prophet Joel,
that in the latter times he would pour out his spirit upon sons and daughters,
servants and handmaids, and they should prophesy,
has in these times measurably made good his promise
by sending forth his servants and handmaids,
to make known his truth, and declare his name, in the demonstration of his mighty power.
Among others who were thus called in this Gospel-day,
Sarah Blackbury came to the town of Hammersmith, in Middlesex,
being five or six miles out of the city to the westward,
and there desired to have a meeting; and the Lord wrought so on Hester Matson,
who lived there, that she received this servant of the Lord into her house,
and acquainted her husband therewith, at his coming home,
(he then belonging to a brew-house in Westminster,
rarely came to his wife and family above once a week;) and desired he
would give leave that a meeting might be appointed at their house,
to which he consented.
But it being at this time, according to the saying of old,
"`They shall say all manner of evil against you falsely for my sake,`" (the evildoers,
even to this day, hating the light,) when the second meeting was to have been held,
he being a man of a high spirit,
and having given ear to the calumnies and bad reports with
which his fellow servants and others had possessed him,
would not permit the meeting to be at his house, notwithstanding his former promise;
whereupon his wife and some few more went to Chiswick,
a town to the westward by the water-side, hardly a mile further,
and for some time had a meeting there, at William Bond`'s house.
It being pretty quickly thought fit to remove nearer Hammersmith,
a place was accordingly provided near the Lime-kilns, by the water-side; called the Hope,
being about mid-way between the two towns; at which Gilbert Latey was a frequent visitor.
In a while after, the meeting was brought back to Hammersmith,
and there continued forty-nine years, and still remains a meeting; during which time,
he was a frequent attender, and in measure the supporter thereof,
being as a nursing father thereto; and the Lord blessed his unwearied love.

About this year there was a meeting opened at Barking m Essex, which is still continued;
and another at Greenwich, in the house which was the king`'s,
of which Gilbert was a frequent visitor,
often going in great hazard from the rude people,
by whom both he and other Friends were often sorely stoned; and when Friends were met,
they would throw stones through the windows, and sometimes injured several;
in all which the Lord upheld and supported Friends; so that,
notwithstanding the rage of the enemy,
they kept up the meeting till the coming of King Charles,
who took possession of the house.
About the year 1658, George Bayle, an apprentice in the New-Exchange in the Strand,
was convinced, and was a very hopeful young man; and some time after went for France,
and being never more heard of,
was supposed to be privately murdered there for his zeal for the Lord and his truth,
in bearing testimony against their idolatry and superstition.
Gilbert in these days was not only made helpful to the Lord`'s servants under sufferings,
but by taking heed to the light of Christ, was endued with such an understanding,
that he saw the spirit of the world began to prevail
again on some who had received the truth,
and now through the enemy`'s subtle workings began
again to draw back from the way of the Lord,
letting self up to get a party; against which he bore his testimony.
He also withstood John Perrot, and gave his judgment against that exalted spirit,
whereby he was entangled, and brought at last into bondage.

Gilbert having enlisted himself under the banner of the Lord,
made profession of his blessed truth, and taken up the cross, despising the shame,
bearing scorn and reproach, it pleased the Lord to bring a trial upon him,
like the cutting off the right hand, or pulling out the right eye.
For being still in great business in the world,
and concerned with persons of considerable rank,
who would have their apparel set off with much cost and superfluities of lace and ribbons,
he came under a conscientious concern not to meddle therewith,
nor allow his servants to put it on; which made some say he was mad.
Upon his refusing to be concerned in this superfluous part,
the great people left him and his trade decayed so, that having a great many servants,
he was forced to part with them; not knowing but he,
who lately had such a great business and so many servants,
might now himself be a servant to some of the trade,
and work at day labour for his bread.
This was a close trial; but he patiently waited the Lord`'s season;
though despised even of his own mother`'s children,
and as it were banished from his father`'s house,
yet he chose to leave all rather than to lose his peace with the Lord.
And He who never forsakes those who trust in him was his support,
bore up his spirit through all his exercises,
and enabled him to be resigned and contented in his will.

Soon after this the Lord opened his mouth in the ministry,
to make known the truth to others.
Having considerable interest and acquaintance with great persons,
the Lord wrought on his heart to solicit them in
behalf of some of his poor brethren and sisters,
who were sufferers for their testimony,
and keeping their consciences clear in the sight of the Lord;
for which several were cast into prisons, and loathsome holes and dungeons.
This was in the time when the government was carried on in the name of Oliver Cromwell,
the Protector, wherein the people had a great seeming zeal,
but not according to knowledge,
and the Lord laid it upon many of his servants to go to and fro in the nation,
both into markets and steeple-houses, that knowledge might be increased,
the blind guides detected, and truth declared.

In the year 1659, he found a necessity upon him from the Lord,
to go to several of their steeple-houses, which they called churches,
and bear testimony against those who had set themselves
up over the people as ministers of Christ,
and yet were such as the Lord complained of by his prophets of old,
"`who preached for hire, and divined for money, running when the Lord never sent them,
teaching for doctrines the commandments of men,
and seeking their gain from their quarter,
and crying peace to the people in their sins.`"

At Dunstan`'s in the west in Fleet-street, after the preacher had ended his sermon,
Gilbert warned the people to take heed to their ways, adding,
that while people are workers of iniquity, they are,
according to the saying of our blessed Lord,
"`of their father the devil,`" and doing his work,
and an abomination in the sight of God; and while they regard iniquity in their hearts,
the Lord will not hear their prayers.
Upon this, the people in the steeple-house seemed all in a ferment;
the constable was called for, who with others took hold of Gilbert,
and haled him away out of their place of worship,
and afterwards carried him before a justice, who lived near the Grange,
in Little Lincoln`'s-inn-fields.
He desired the justice would be pleased to hear him patiently,
for at this time people were so far strayed from the way of truth,
that they were in a great measure strangers thereto,
and the Lord`'s people were as speckled birds,
and all manner of evil was spoken against them falsely for Christ`'s sake.
Whereupon the justice, like king Agrippa, permitting him to speak for himself, he said,
that he was moved of the Lord,
as some of the Lord`'s servants had been of old to go into the synagogues,
to go that day to Dunstan`'s steeple-house,
where finding one called Doctor Manton preaching,
and holding forth false doctrine to the people, he stayed till he had finished his sermon,
and then, before he entered into his prayer, charged him to prove his doctrine,
for that he was conscientiously dissatisfied therewith, as being erroneous.

The justice seemed to admire at what he had related,
and said that Doctor Manton was a very learned man,
and doubtless could make out by Scripture what he had preached that day.
Gilbert replied, all he desired was, that according to Scripture,
he would make good what he had preached to the people, but could not obtain it:
upon which the justice asked the constable whether, what Gilbert had thus alleged,
was true,
and whether that was the only matter for which he had brought the man before him?
To which the constable answered, That was the whole matter.
Then the justice replied,
that he had heard those people called Quakers were a sort of mad, whimsical folks; but,
this man talks very rationally, and I think, for my part,
you should not have brought him before me; to which the constable replied.
Sir, I think so too.
Gilbert had a few words in his heart to the justice, concerning the way of the Lord;
whereupon the justice desired the constable to take him away, saying,
he was come there to preach to him also.
Then the constable and Gilbert went away together,
and he was left at his liberty to go where he pleased.
After this he several times accidentally met with Manton,
and still challenged him to prove his doctrine, which he never could;
and at last meeting him in Westminster Abbey, he followed him close,
and asked him again to prove his doctrine; to which Manton said,
he was not able to prove it as Gilbert would have it; to which Gilbert replied,
"`If you had told me so sooner, I had been better satisfied,`" and so left him.

After the breaking forth of the truth,
Gilbert was committed to the Gate-house prison in Westminster,
together with about fifteen or sixteen of his friends,
for meeting together in the fear of God to worship him.
They were all put into a dungeon, or hole,
which was about ten feet wide and eleven feet long,
and so dark that they could see no more light at mid-day than at mid-night.
The walls of it were wet, and they being pressed in so narrow a compass,
had room only to lie down by turns; so that while some lay down to rest,
others were forced to stand.
The keeper was so cruel as to command the turnkey
not to admit a little straw to be brought in,
to be put on the ground for them to lie on; but the Lord was with them,
and supported them under all the cruelty that was indicted upon them,
for the trial of their faith and patience; and delivered them from their sufferings.

The spirit of persecution raged in many parts of the nation,
and many hundred Friends being put into prisons, houses of correction and dungeons,
a paper was drawn up and presented to a meeting of persons called a Parliament,
or Committee of Safety, to whom one Glanvil was speaker, or chairman.
The paper being delivered to him, was read, and was to this effect, That Gilbert,
and the Friends present,
desired their friends who were under these severe sufferings and confinement,
might be set at liberty; and that they were willing to go into prison in their steads.
This was not accepted.
Towards the latter part of Cromwell`'s time.
Friends were under great sufferings; and many were committed to prison in various places;
and among the rest, some to the Gate-house and Bridewell in Westminster,
where they met with severe and hard usage from the master of the Gate-house,
whose name was Wickes.
He demanded a noble from each person,
besides seven shillings a week a piece for their
bed (although there were three beds in a room,
and two persons lay in a bed,) besides garnish-money;
for which they suffered the taking away of their clothes,
which were disposed of for the demand; and as for bread or beer,
they could only have it according to the prison rates.

Gilbert seeing all this, was very much troubled not only at his severity,
but that many who were cleared, lay after this miserable manner for their fees,
some of whom died in prison.
He therefore delivered to the justices of peace for Westminster,
a paper which he had drawn up, setting forth these grievances.
It was received and read by Sir William Wheeler, who was in commission for the peace,
but not being then well, he promised,
that if it should please the Lord to enable him to go abroad again,
he would call to account the matter complained of.
In some short time, God in his mercy having restored him and enabled him to get abroad,
he opened the matter on the bench of justices, and an order was made,
that Gilbert should bring witnesses to prove his allegations.
The witnesses being two prisoners then in custody,
the master of the prison made it his business as much as in him lay,
to hinder Gilbert from producing such evidence as the bench of justices directed,
and therefore turned out of prison all such as lay for their fees.
The day appointed for hearing the matter being at hand,
he hoped by that means to frustrate Gilbert from producing evidence to prove his charge;
but notwithstanding Wickes`'s cruelty and subtlety,
it pleased God to order things to be so brought to light,
that the very morning the matter was to come to a hearing, two women in good habit,
having by some means heard of this business, came from the post-house, at the White-hart,
Charing-cross, and informed Gilbert,
that their husbands were kept in the Gate-house prison for fees till they both died.
Upon this, Gilbert and another Friend, having got the evidence drawn up,
and signed by the women, approached the court; and the matter being called, Wickes,
the master of the prison, appeared, and Gilbert`'s charge against him was read.
He having a couple of Friends there with him who were prisoners, to attest the charge,
as well as the evidence under the two women`'s hands,
the justices asked the two Friends if they were witnesses; to which they replied,
they were,
and that the matter there read and complained of was true whereupon
the justices told Wickes they would call all these things to account.
Wickes returned home, and the Friends who were in the court,
not being wholly cleared of the prison, followed him,
and asked him what they had to pay for their lodging.
He, like one who had received a mortal blow, answered faintly,
"`What they pleased,`" and so went into his house,
and continued ill about three or four days, and in that time cried out, and said,
"`God will cut me off in the midst of my iniquity,`" and so died.
Notwithstanding all this his widow repented not, but grew more hardened;
and some time after was married to one Major Rroughton,
and was more wicked if possible than before.

Friends were now under sufferings for their consciences in Maryland,
notwithstanding they were some of the first planters there,
and had large promises of liberty and freedom made to them,
upon their going to settle there.
The old adversary stirred up some to inflict hardship
upon them on account of their tender consciences;
and Gilbert often attended the lord Baltimore, who was chief proprietor of that country,
on the behalf of these sufferers, for their relief;
and God blessed his attendance and solicitation, and it had a place with him,
so that he was prevailed upon for the ease of Friends there.

In the year 1660,
it having pleased the Lord to lay a necessity on two of his servants and handmaids,
namely, Catharine Evans and Sarah Cheevers, to visit various parts beyond the seas,
warning the people to turn to the Lord; after having passed through several countries,
they arrived at the island of Malta, where,
for bearing testimony to the power of God revealed in and
through our Lord Jesus Christ by his spiritual appearance,
they were taken up and confined.
The tidings of this, some time after, came to London,
and Gilbert being often engaged in soliciting ease for the suffering,
made it his business to find out who had an interest in those parts;
and after some time and pains spent in this affair, he got information,
that one lord D`'Aubigny who came over with the queen-mother,
and was lord almoner to her, had both interest and command in the island of Malta.
When Gilbert had obtained this knowledge, he soon got access to him,
and found him to be a well-tempered man;
and notwithstanding the way of the Lord was evilly spoken of,
and his people were looked upon by many as speckled birds,
and went as with their lives in their hands,
the power of God so wrought on this lord D`'Aubigny, although he was a priest in orders,
that he was very kind and free to Gilbert, and reasoned with him like Felix with Paul,
about the principles of truth and way of the Lord;
and being informed concerning the power of God and the manner of the spirit`'s working,
answered, that some of their people thought our friends were mad; but, said he,
I do not think so of them.

In discourse with him at another time, he said, Let me talk with you ever so long,
you will still tell me of the spirit of God, and the grace of God,
and the work and operation thereof,
and the love of God you are made witnesses of through Jesus Christ,
which I believe may in a measure be true;
but do you not think it is well to have something
to represent that which you so much love?
To which Gilbert answered, that the substance of all things is come,
Christ in us the hope of glory, and all the outward types,
representations and shadows must come to an end, and be swallowed up in our blessed Lord;
who told his disciples it was expedient for them he should go away; but, said he,
I will not leave you comfortless.
If I go not away, the Comforter will not come; but if I depart, I will send him unto you,
even the spirit of truth, which shall guide you into all truth;
and also that He who was with them should be in them.
This being witnessed, there needed nothing outwardly to represent or put them in mind,
for He being so near, was himself the saints`' daily remembrancer.
Upon this they parted; but Gilbert often visited him,
to desire and remind him to show kindness to the Friends
that were under confinement in a strange place,
and at so great a distance from their friends and their native country.

Coming another time to wait on him, he bid Gilbert follow him;
and went into the queen`'s chapel, where Gilbert seeing the people on their knees,
and the candles lighted on the altar, made a halt,
and asked the lord D`'Aubigny what he meant by bidding him come there, for, said he,
you knowest I can bow to nothing here; upon which he answered, "`Follow me,
and no body shall hurt you, nor meddle with you.`"
Gilbert followed him through the chapel to a room behind the altar,
where was another of the queen`'s priests; and there being some lesser altars,
the lord D`'Aubigny said to Gilbert, "`You never yet saw me in my priestly habit,
but now you shall;`" and while he was making ready,
the power of the Lord worked so much on Gilbert,
that he stepped up on a place they called a private altar,
and began to preach truth unto them.
Among other expressions, he observed,
"`We have an altar of which you have no right to eat.`"
Whereupon the queen`'s priest asked, "`What altar is this you speak of?`"
said Gilbert, "`The altar I speak of,
is that on which the saints daily offer up their
prayers to the living God:`" the priest replied,
"`Friend,
there is no greater state attainable than what you
speak of;`" and so they parted again for that time.

Gilbert ceased not to visit the lord D`'Aubigny,
still renewing his request for kindness to be shown to his suffering friends;
and some time after, going to wait on him,
to see if he had any answer to letters which he had promised to write on their behalf,
he acquainted Gilbert that his friends were at liberty; which was joyful news to him.
Some time after, they arrived in England, came to London, and went to visit Gilbert;
and after acknowledging his love and endeavours for their liberty,
desired him to bring them to see the lord D`'Aubigny,
whom the great God had made an instrument of their enlargement out of severe imprisonment.

Gilbert was very willing to accompany them, and according to their desire,
went with them to wait on the lord D`'Aubigny.
When they came, and he understood Gilbert was desirous to have the liberty of seeing him,
he came to them;
and Gilbert told him his friends who were made partakers of his great kindness,
and released of their bonds in Malta,
were now come to pay their acknowledgments to him for the same.
He asked if they were the women.
To which they replied, they were; and as the Lord put it into their hearts,
they spoke to him; adding, that were it in their power,
they should be as ready in all love to serve him; upon which he replied, "`Good women,
for what service or kindness I have done you, all that I desire of you is,
that when you pray to God, you will remember me in your prayers;`" and so they parted.

Upon the coming in of King Charles II. great part of the
nation was so transported in idolatry and excess,
and many into madness, and so far wandered from the Spirit of God,
and slighted the motions thereof,
that to wait upon the Lord for its renewings was accounted a crime.
Friends having then a meeting at Stephen Hart`'s house,
in the New Palace Yard in Westminster; on the third-day of the week in the forenoon,
according to their usual manner,
Gilbert and some others were met there to worship the Lord,
as they were conscientiously persuaded was their duty;
waiting upon him to feel his refreshing presence and love shed in their hearts.
As they were thus met, two parties of foot soldiers came,
the one being of the trained-bands, the other of the king`'s foot-guards;
and they differed among themselves, which should first lay hold of Friends;
but the guards being the stronger party, took them into their custody.
He who commanded them, laid hold of Gilbert, and told him that he was his prisoner,
and all he had about him was his plunder: upon which Gilbert said,
"`If I am your prisoner, and all about me your plunder,
I charge you in the name of the Lord, that you see no man hurt me,
nor my friends;`" for what with the trained-bands and the guards,
and the flocking of the people, a great rude company was got together.
As the officer led Gilbert through them, he said, and bound it with an oath,
that if any of them harmed the prisoners, he would endeavour to be the death of them.
Gilbert was carried away prisoner, and put under the Banqueting-house at White-Hall,
where the presence of the Lord accompanied him to his great comfort and satisfaction,
in more than an ordinary manner, and he had good service there for the Lord.

Notwithstanding the trials which attended the people of God in these days,
his power prevailed, and the truth prospered,
and many were convinced and turned to the Lord.
Among these, Elizabeth Trott having received the truth, gave up her house,
which was towards the end of the Pall Mall, near James`'s house, for a meeting,
which in a great measure was settled by Gilbert,
who was a very constant attender thereof;
and having acquaintance with a justice of peace who lived thereby,
had often prevailed to induce him to moderation.
But at last he told Gilbert, that our meeting being so near the duke`'s palace,
he had been much blamed about it,
and now had received positive command to put the laws in execution,
and disperse the meeting; adding, "`I can no longer forbear coming,
in order to prosecute the commands laid upon me by so high and eminent a hand,
as his that has given me this matter in charge.`"
However, Gilbert could not forbear, but as he was persuaded was his duty,
observed the command laid on the people of God,
not to forsake the assembling of themselves together, and went to the meeting,
it being about the latter part of the year 1662.
The justice, according to the command he had so positively received,
broke up the meeting, and Gilbert and another public Friend were carried away prisoners,
and afterwards Friends were often kept out, and met in the street;
and although they were several times taken and confined,
yet Gilbert was still a frequent and constant attender.

Persecution was very heavy, not only in this city and suburbs,
where many were under confinement, for meeting to worship the Lord;
but the same spirit was at work in other parts of the kingdom,
and Friends underwent great sufferings and hardships in most counties,
and the people were in a light libertine spirit,
having little consideration of the "`affliction of Joseph,`" but were very high, proud,
and loose.

The Lord God of heaven beholding that people`'s hearts were thus exalted,
and his fear trampled upon, shook his rod over this great city, and brought a pestilence,
which swept away about a hundred thousand of its inhabitants.
This was in the year 1665,
and Gilbert had taken lodgings in order to go into the country;
but as many Friends were under close confinement
in several jails for the testimony of a good conscience,
particularly in Newgate, the Gate-house in Westminster, and other prisons,
Gilbert could not find freedom to leave the city, to go and be at ease,
while his brethren were thus under sufferings, and therefore continued there;
and according to his normal manner, visited them in the jails,
and endeavoured that nothing should be lacking for their support, or,
according to his power, to procure their enlargement.

[.embedded-content-document.testimony]
--

+++[+++Editor`'s Note: It will doubtless be interesting to our readers,
to have a more particular account of this solemn visitation of divine judgment.
The period at which it broke out, was one of very severe persecution.
Hundreds of Friends were in the prisons,
and many on board vessels in the river under sentence
of banishment for their religious principles.
The fury of the oppressor seemed nearly to have reached its height,
when it pleased the Most High to bring this calamity on the city,
which was the very fountain of persecution.
Many Friends beside Gilbert Latey, remained in the city during the whole time;
and though according to the saying of Holy Scripture,
"`One event happens to the righteous and the wicked`" at such times;
the Lord being pleased to take his servants unto himself,
yet there were many remarkable instances in which
preservation was vouchsafed to those who,
from motives of benevolence and of religious duty,
spent their time in relieving the distresses of their suffering fellow creatures.

It is a fact deemed worthy of notice by many at that time,
that the disease first broke out in Bear-binder`'s lane,
in a house adjoining that in which Edward Brush resided,
a Friend who had just previously been banished from his native country for his religion.

Among the many calamities with which the Almighty
is pleased to visit the children of men,
in order to reduce them to a just sense of their
own weakness and entire dependence upon him,
there is scarcely any more productive of true penitent humiliation,
and of a sight of what is really good and truly evil, than those contagious distempers,
which an offended God sometimes allows to rage among the people.
In the year 1665 the city of London was sorely visited by the plague:
An account of the progress and effects of that visitation was kept by
a citizen who remained there during the whole time of the sickness,
and appears to have been candid and judicious in his remarks thereon.
I trust my readers may, in a short description of that memorable judgment,
meet with lessons of best wisdom,
which nothing can so effectually teach as a close
and serious converse with death and the grave.
The introduction of this contagion into London was by some goods imported from Holland,
which had been brought there from the Levant.
It first broke out m the house where those goods were opened,
from which it spread to other houses.
In the first house that was infected four persons died:
A neighbour who went to visit them returning home, gave the distemper to her family,
and died with all her household.
The parish officers who were employed about the sick persons, being also infected,
the physicians perceived the danger, and,
upon narrow inspection were assured that it was indeed
the plague with all its terrifying particulars,
and that it threatened a general infection.

The people began now to be alarmed all over the town;
the usual number of burials within the bills of mortality
for a week were generally about 240 to 300,
but from the 17th to the 24th of January,
the printed bill was 474. However this went off again,
and the frost continuing very severe till near the end of February, the bills decreased,
and people began to look upon the danger as good as over;
but in May the bills greatly increased, and the weather becoming hot,
the infection spread again in a dreadful manner.

[.small-break]
'''

"`I lived,`" says the author, "`without Aldgate,
and as the distemper had not reached to that side of the city,
our neighbourhood continued easy; but at the other end the consternation was very great,
and the nobility and gentry thronged out of the town
with their families in an unusual manner.
Nothing was to be seen but wagons, carts and coaches with goods and people,
and horse-men attending them, hurrying away; then empty wagons and carts appeared,
apparently returning to fetch more people, besides numbers of people on horseback,
fitted out for travelling.
This was a very melancholy prospect; indeed there was nothing else of moment to be seen.
It filled my mind with very serious thoughts of the misery that was coming upon the city,
and the unhappy condition of those that would be left in it.

By the end of July the contagion had spread to a great degree:
Sorrow and sadness sat upon every face; and though some parts were not yet overwhelmed,
all looked deeply concerned.
London might well be said to be all in tears.
The mourners did not go about the streets;
nobody made a formal dress of mourning for their nearest relations,
but the voice of mourning was indeed heard in the streets;
the shrieks of women and children at the windows and doors
of their houses where their dearest relations were dying,
were so frequently to be heard as we passed the streets,
that it was enough to pierce the stoutest heart.
Tears and lamentations were seen almost in every house,
especially in the first part of the visitation for towards the latter
end people did not so much concern themselves for the loss of their friends,
expecting that themselves should be summoned the next hour.

It was a time of very unhappy breaches among us in matters of religion,
divisions and separate opinions prevailed.
The Church of England was lately restored,
and the Presbyterians and other professions had set up their meetings for worship,
in which they were frequently disturbed, the government endeavouring to suppress them.
But this dreadful visitation reconciled the different parties,
and took away all prejudice and scruple from the people.
But after the sickness was over, that spirit of charity subsided,
and things returned to their own channel again.
Here we may observe,
that a nearer view of death would soon reconcile men of good principles to one another,
and that it is chiefly owing to our easy situations in life,
and our putting these things far from us, that dissensions are fomented,
and that there is so much prejudice and lack of Christian charity and union among us.
A close view and converse with death, or with diseases that threaten death,
would sweeten our temper, remove our animosities,
and bring us to see with different eyes.
On the other side of the grave we shall all be brethren again.

The inns of court were all shut up, there were few lawyers to be seen in the city,
indeed there was no need of them, for quarrels and divisions about interest had ceased;
every body was at peace.

It was also worthy of observation, as well as fruitful of instruction,
to observe with what alacrity the people of all persuasions embraced
the opportunities they had of attending upon the public worship,
and other appointed times of devotion, as humiliations,
fastings and public confessions of sins, to implore the mercy of God,
and avert the judgment which hung over their heads.
The churches were so thronged, that there was often no coming near, no,
not to the very door of the largest.
There was also daily prayers appointed morning and evening,
at which the people attended with uncommon devotion.

All plays and interludes which had lately began to increase among us, were forbidden;
the gaming-tables, public dancing-rooms and music houses,
which had multiplied and began to debauch the manners of the people,
were shut up and-suppressed, finding indeed no trade;
for the minds of the people were generally humbled and agitated with other things:
death was before their eyes, and every body began to think of their graves.

The infection still gradually increased till the middle of August,
when there died a thousand a day, by account of the weekly bills,
though they never gave a full account by many thousands;
many of the parish officers were taken sick themselves
and died when their account was to be given in.
The parish of Stepney alone had within the year, one hundred and sixteen sextons,
gravediggers, and carriers of the dead, etc.
Indeed the work was not of a nature to allow them
leisure to take an exact tale of the dead bodies,
which were all thrown together in the dark in a pit,
to which no man could come near without the utmost peril.

I had, says the author, the care of my brother`'s house,
which obliged me sometimes to go abroad.
In these walks I had dismal scenes before my eyes, as, particularly,
of persons falling dead in the streets, shrieks of women,
who in their agonies would throw open their chamber-windows,
and cry out in a melancholy manner.
It is impossible to describe the various ways in which the
passions of the poor people would express themselves.
Passing through Token-house yard,
of a sudden a casement violently opened just over my head, and a woman cried: '`Oh!
Death, Death, Death,`' which struck me with horror and a chilness in my very blood.
There was nobody to be seen in the whole street, neither did any window open,
for people had no curiosity now in any case.

Death did not now hover over every one`'s head only,
but looked into their houses and chambers, and even stared in their very faces;
and though there was some stupidity and dulness of mind,
yet there was a great deal of just alarm sounded in the inmost soul.
Many consciences were awakened; many hard hearts melted into tears;
many a penitent confession was made of crimes long concealed.
People might be heard even in the streets as we passed along, calling upon God for mercy,
through Jesus Christ, and saying: I have been a thief; I have been an adulterer;
I have been a murderer, and the like;
and none dared stop to make inquiry into such things,
or to administer comfort to the poor creature,
who in the anguish both of soul and body thus cried out.

Many were the warnings that were then given by dying penitents to others,
not to put off their repentance to a day of distress,
and that such a time of calamity as this was no time for repentance.
I wish, says the author,
I could repeat the very sound of those groans and
exclamations that I heard from some poor dying creatures,
when in the height of their agonies and distress,
and that I could make him that reads this hear, as I imagine, I now hear them,
for the sound seems still to ring m my ears.
In the beginning of September the number of burials increasing,
the church-wardens of Aldgate parish ordered a large pit to be dug,
to hold all the dead who might die in a month,
it was about forty feet long and sixteen broad.
Some blamed the church-wardens for allowing such a frightful gulf to be dug;
nevertheless in two weeks they had thrown more than eleven hundred bodies into it,
when they were obliged to fill it up,
as the bodies were come within six feet of the surface.

I must not omit mentioning the disposition of the people of that day,
with respect to their charity to the poor,
which indeed was very large both m a public and a private way.
Some pious ladies were so zealous in this good work,
and so confident in the protection of Providence in the discharge of this great duty,
that they went about themselves distributing alms,
and visiting the poor families that were infected, in their very houses,
appointing nurses and apothecaries to supply them with what they needed;
thus giving their blessings to the poor in substantial relief,
as well as hearty prayers for them.
I will not undertake to say,
that none of these charitable people were allowed to die of the plague,
but this I may say, that I never knew that any of them died,
which I mention for the encouragement of others in case of like distress; and doubtless,
if they that give to the poor lend to the Lord, and he will repay it,
those that hazard their lives to give to the poor,
and to comfort and assist them in such a misery as this,
may hope to be protected therein.

From the middle of August to the middle of September
the infection still increased and spread itself,
with an irresistible fury.
It was reckoned, that during that time there died no less than sixteen hundred a day,
one day with another.
It was then that the confusion and terror was inexpressible.
The courage of the people appointed to carry away the dead, began to fail them:
the vigilance of the magistrates was put to the utmost trial.
At last the violence of the distemper came to such a height,
that the people sat still looking at one another, and seemed quite abandoned to despair.
In a word, they began to give themselves up to fear,
that there was nothing to be expected but a universal desolation.
Despair made them bold and venturous, they were no more shy of one another,
as expecting there was now no avoiding the distemper, but that all must go.
This brought them in crowds to the churches;
they inquired no more what condition the people who sat near them were in,
but looking upon themselves also as so many dead corps,
they came to the churches without the least caution, and crowded together,
as if their lives were of no consequence,
compared to the work which they were come about.
Indeed, their zeal in coming,
and the earnestness and affectionate attention they showed to what they heard,
made it manifest what value people would put upon the worship of God,
if they thought every day they attended would be their last.

It was in the height of this despair, that it pleased God to stay his hand,
and to slacken the fury of the contagion,
in a manner as surprising as that of its beginning,
and which demonstrated it to be his own particular hand above the agency of means.
Nothing but omnipotent power could have done it.
The contagion despised all medicine: death raged in every corner,
and had it gone on as it did then,
a few weeks more would have cleared the town of all its inhabitants.
In that very moment when thirty thousand were dead in three weeks, no,
when it was reported three thousand died in one night,
and a hundred thousand more were taken sick, when we might well say.
Vain was the help of man, it pleased God to cause the fury of it to abate,
and by his immediate hand to disarm the enemy.
It was wonderful!
The physicians were surprised, wherever they visited, to find their patients better,
and in a few days every body was recovering.

Nor was this by any medicine found out, or any new method of cure discovered;
it was evidently from the secret invisible hand of him that had at first sent this disease,
as a judgment upon us.
Let the philosophers search for reasons in nature to account for it,
and labour as much as they will to lessen the debt they owe to their Maker;
those physicians who had the least share of religion in them,
were obliged to acknowledge, that it was all supernatural.
The streets were now full of poor recovering creatures,
who appeared very sensible and thankful to God for their unexpected deliverance:
Yet I must own, that as for the generality of the people,
it might too justly be said of them, as was said of the children of Israel,
after they had been delivered from the host of Pharaoh, that they sung his praise,
but soon forgot his works.`"

[.small-break]
'''

The author, who was preserved unhurt with his whole family,
during the time of the sickness,
gives a particular account of the reasonings and fears which affected his mind,
before he could come to a fixed conclusion, whether to stay,
and take his lot in the station in which God had placed him, or by leaving the city,
run the hazard of unsettling himself At the earnest solicitations
of his brother he had concluded to go;
but being always crossed in this design by accidents, it came one morning,
as he expresses it, very warmly in his mind,
whether these repeated disappointments were not intimations to him,
that it was the will of heaven he should not go.
This was succeeded by a further thought, that if it was from God,
he was able effectually to preserve him in the midst
of all deaths and dangers that would surround him,
and that if lie attempted to secure himself, by fleeing from his habitation,
and acted contrary to these intimations, which he believed to be divine,
it was flying from God, who could cause his justice to overtake him,
when and where he thought fit.

But what finally fixed him in a resolution to stay,
and cast himself entirely upon the protection and good pleasure of the Almighty was,
that at a time when his thoughts were more than commonly serious upon this weighty subject,
turning over the Bible which lay before him, he cried out, '`Well, I know not what to do,
Lord direct me!`' at that juncture happening to stop and
casting his eye on the second verse of the 91st Psalm,
he read to the tenth, as follows: '`I will say of the Lord,
he is my refuge and my fortress, my God, in him will I trust.
Surely he shall deliver you from the snare of the fowler, and from the noisome pestilence.
He shall cover you with his feathers, and under his wings shall you trust:
His truth shall be your shield and buckler.
You shall not be afraid for the terror by night, nor for the arrow that flies by day,
nor for the pestilence that walks in darkness,
nor for the destruction that wastes at noon-day.
A thousand shall fall at your side, and ten thousand at your right hand;
but it shall not come near you.
Only with your eyes shall you behold and see the reward of the wicked.
Because you have made the Lord which is your refuge, even the Most High your habitation:
There shall no evil befall you,
neither shall any plague come nigh your dwelling,`' etc.]

--

[.offset]
Returning to the Life of Gilbert Latey.

In this time of sore exercise, he was also engaged in visiting Friends in their families,
as well those under sickness, as others whom the Lord had in measure restored again;
and the Lord inclined several Friends in the country,
to consider the poor who were under this great calamity,
and accordingly they sent money to be distributed,
a part of which was allotted to the poor people who were ill with the sickness,
but more especially to those who were shut up in
their houses in the out-parishes without Temple Bar.
This service was committed to the care of Gilbert, and one other Friend,
to visit the poor, particularly those who were confined to their own houses,
and as near as they could they neglected none,
but went and administered the charity to them, many of whom had running sores upon them;
and the Lord was with him to preserve him in health.

After the contagion was much abated, and the mortality decreased,
there happening a matter of difference,
Gilbert was chosen an arbitrator for putting an end to it;
and the hearing of both parties taking much time,
and all the while sitting in a cold damp room, he felt the cold strike to his heart;
and as most illness then turned to the plague, he suddenly grew very ill;
but the Lord was good to him, and having further service for him, raised him up again.

In the year 1666, Friends belonging to that end of the city,
agreed to remove the meeting from Pall-Mall more among the body of Friends,
there being very few houses then in the Mall except on the side next the Park,
the other side being a great row of large elm trees
and that which is now the market and the square,
and all thereabouts being fields.
Westminster being the residence of several Friends,
and a great concourse of people that way,
Gilbert and some Friends sought to get a place for a meeting in those parts,
and accordingly they bought the lease of a house
and garden in the Little Almonry in Westminster,
and immediately paid down the purchase money,
and the meeting has continued there ever since.

The Lord by the visitation of pestilence upon the city, had both thinned the people,
and made grass grow in the streets, of both which his servants had forewarned the people,
that they might repent.
But they not being humbled, still persisted in their former loose course of life,
and continued in that persecuting spirit which strove to lay waste the heritage of God,
by imprisoning, banishing, and despitefully using his children and servants,
their hearts being hardened against the Lord; and his counsel,
through his messengers being slighted, and profaneness too much encouraged,
to the grief of the upright-hearted.
The great God beholding these things,
permitted the devouring flames to consume the dwellings of thousands,
and their costly furniture, and hereby opened the prison doors,
laying 13,000 houses in ashes.
Gilbert being a partaker with his brethren then under sufferings,
and an eye witness of what is here related, did warn some of this impending judgment;
and was desirous that those who are the children of that
persecuting generation which the Lord thus visited,
into whose hands this may come, might take warning and return to the Lord God.

In the year 1670, about the sixth month,
it being a time of great suffering generally through the nation,
Gilbert had it upon his mind to visit his native country, the west of England.
He took his way through Reading,
where he visited Friends who wore prisoners for the testimony of their consciences;
and having been refreshed together, he went from there to Bristol,
and had a good meeting with Friends.
From there he took his way through Bridgewater, and after visiting Friends there,
passed on to South-Moulton, and from there into Cornwall,
where he had several good meetings, and went towards the Land`'s-end.
At John Ellis`'s, not far from there, he had a meeting on the first-day of the week,
and the Lord`'s power preserved him;
and the next morning riding to visit some Friends very near the Land`'s-end,
he met the persecuting justice, who, as Gilbert was afterwards acquainted,
was very much displeased that his accomplices had failed to give him information,
for he would have seized Gilbert`'s and his man`'s horses, for that day`'s meeting.

After having visited Friends in that part of the country, he came to Penzance,
and Market-Jew; and near Market-Jew,
at a place where there never had been a meeting before, he had a meeting,
to the great satisfaction of several present.
From there he went to Helston, and so to Falmouth and Truro,
and back to Loveday Hamley`'s at Tregangeeves,
having had meetings in several parts of that country.

Upon leaving Cornwall for Plymouth, he received a letter from London,
informing him of the great persecution which attended Friends, as well on their persons,
as by the spoiling of their goods:
and that their meeting-house at Horsleydown was begun to be pulled down,
there being a timorousness in some persons to stand by their title,
and own and defend the same.
Shortly after, by another letter, tidings came that Sir John Robinson,
then governor of the Tower of London,
had given order for pulling down Friends`' meeting-house at Ratcliff, which was done,
for lack of those appearing and owning the title, who were immediately concerned therein.
Another account stated that the governor of the Tower intended
to pull down Friends`' meeting-house in Wheeler-street.
The title of this meeting-house being in Gilbert, and he being away from home,
a Friend was desired to wait on Sir John Robinson,
and acquaint him that the person who owned that meeting-house
was gone a journey into the west of England,
and therefore to desire he would forbear doing what he intended,
till the person that owned it returned: Robinson replied,
"`How long will it be till he return?`"
To which answer was made.
About a fortnight or three weeks: the governor replied,
"`I will then forbear three weeks.`"
By the time the Friend had thus spoken to Robinson,
Gilbert was come to Plymouth in his way back to London; and having visited Friends there,
went to Kingsbridge; and, contrary both to his and Friends`' expectation,
had a peaceable good meeting,
and afterwards spent a little time with Friends who were under great sufferings,
and particularly two young maiden gentlewomen, who had not long been convinced,
and were committed to prison, by a warrant from a justice, whose name was Bare,
for their not coming to the parish place of worship to hear, as they styled it,
divine service.

Gilbert hearing this,
and having an interest in some that were very eminent in the lieutenancy,
and ancient in the commission of the peace,
resolved to use his utmost endeavours and interest,
to procure the enlargement of those women Friends.
Whereupon he ordered his man to take care that his horses might be well fed,
for that he should now travel pretty hard: so he left Kingsbridge,
and it being a very inclement day, came that evening to Exeter;
and after having visited Friends, proceeded to a great knight`'s house,
which was about eighteen miles distant, and not much out of the way towards London.
When Gilbert arrived, the knight was at home, and his gentleman received him very kindly;
and he being well known to the lady and daughters of the family,
soon had access to the knight, who was glad, as he expressed himself,
to see Gilbert in those parts.
The weight of his Friends`' sufferings, and in particular those of the two females,
lay so upon Gilbert, that he immediately importuned the knight for their enlargement;
to which he at last replied,
that he would do more for Gilbert than for all his
friends of his persuasion in the kingdom;
upon which Gilbert acknowledged his kindness, and pressed for his favour in their behalf.

The time of the sessions being near, he desired him to be there,
and to take care that they were called,
lest otherwise they might not be brought before the bench;
and he would use his interest with the justices for their enlargement.
He ordered his clerk to note down and remind him of what Gilbert had said.
Gilbert then took leave of the knight, and his family, and set forward for London,
visiting Friends in his way.
When he arrived at London he ordered a poor Friend to be put into Wheeler-street meeting-house,
to whom he made a lease;
and then desired the Friend who had before attended the governor of the Tower,
to let him know the person who owned the meeting-house in Wheeler-street,
was now come home, and ready to attend him when he should be pleased to appoint.

In a few days Gilbert was ordered to appear before the governor.
He, with the other Friend, went at the time appointed to the governor`'s house,
in the Tower, and was soon called in before him.
He appeared very stern towards Gilbert,
and asked him if he owned the meeting-house where Friends met in Wheeler-street;
to whom he answered, he did, and several more too.
The governor said, "`And how dare you own any meetinghouse contrary to the king`'s laws?`"
To which Gilbert said, that he owned that meeting-house before the king had any such law.
The governor replied, "`I find you are a pretty fellow; and pray,
who lives in the meetinghouse?`"
Gilbert answered, "`My tenant.`"
"`Your tenant!`" said the governor, "`What is your tenant?`"
"`One that I have thought good to grant a lease to,`" said Gilbert.
"`Then,`" replied the governor, "`you have a tenant that has taken a lease from you?`"
Gilbert answered, "`Yes.`"
Upon this the governor looked not pleased, and calling the other Friend by his name,
said, "`I think you have now fitted me, and brought a fellow to the purpose;
had your friends been as wise as this fellow,
you might have had your other meeting-houses as well as this;`" and so dismissed them.
After this, Friends taking the same care, have ever since preserved their meeting-houses.

Soon after this, Gilbert had account by letter,
that at the sessions for the county of Devon,
the knight remembered his promise to Gilbert,
and moderated the justice who committed the two Friends.
As they sat at dinner, he acquainted the other justices,
that he was informed of two young women, Quakers,
that lay in prison for not coming to church; "`and,`" said he,
"`I am very much importuned to use my interest with you for their enlargement,
which I desire you will favour so far that it may be done;
for indeed I think it is a pity they should be longer under confinement.`"
This knight being in so eminent a station, both on the bench and otherwise,
the rest of the justices acquiesced that they should be brought before them accordingly.
"`But, then,`" said the knight, "`when they are brought before you,
and upon examining into the matter, you shall think fit, as I hope you will,
to clear them, there will another hardship attend them; which is,
that after they are cleared by you, they will still be detained for their fees;
for none of them will pay fees, and therefore that they may be wholly at liberty,
we must, among ourselves,
collect as much money to give the jailer as will answer their fees; and,`" said he,
"`here I will begin:`"--laying down money on the table, and the rest did the like.
The Friends being brought before them on the bench,
were cleared and set at liberty to return to their habitations,
which they did accordingly; for which favour Gilbert, according to his customary manner,
returned the knight his acknowledgment.

As he kept to the truth, still bearing the cross of Christ,
it came upon him to write something by way of caution
and encouragement to such as were of the same trade,
that they might know the power of it to lead them out of superfluity,
and be a means to persuade and advise others therefrom;
whereby that which tended chiefly to gratify the proud, loose, high mind,
might as much as in them lay, be discouraged; the needless part be relinquished,
the vain mind brought down, and truth and a good conscience kept to,
for which he wrote the following paper;
and being communicated to several Friends of the same trade,
they were well satisfied with it, and desired it might be printed, as follows:

[.embedded-content-document.paper]
--

[.letter-heading]
A Salutation or Testimony of true and brotherly love, unto all who are concerned therein.

[.salutation]
Dear Friends,

To whom the truth of God has appeared,
and has been made known in the light of his beloved Son,
whom he has sent into the world to discover the ways of sin,
in the hearts and consciences of the children of men; that so all may depart from them,
as they are made known to them by the light that shines in their hearts,
which is the standard to try all by, and the balance to weigh all in,
of what sort soever, whether it be of God or no.
And this is the rule for us to walk by, even the law of light,
which gives life and salvation to all that believe, and therein abide.
This it was which first gathered us together,
and raised desires in us after the Lord`'s way, with which our souls are refreshed,
and our spirits comforted and consoled in the enjoyment of it,
more than with our appointed food.
When we have met together to wait upon him in his heavenly way,
he has filled our hearts with his dew,
and refreshed us as with the early and latter rain;
and here we came to feel the Lord`'s power revealed,
who works all our works in us and for us, by the operation of his own eternal spirit,
by which he is cleansing his sanctuary, and making vessels fit for the Master`'s use,
for life to reign in; that the love of God may overflow in all,
inviting the nations to come and walk in the light of the Lamb, and be saved.
This is that which we have breathed unto the Lord for, as for ourselves,
that so all may come to the knowledge of the truth, and be saved.
Wherefore dear Friends, mind God`'s leading in all things whereunto you are called,
and therein abide with the Lord,
keeping a conscience void of offence towards God and man:
that so the truth may be adorned in us all, by a holy life and godly conduct,
as becomes the Gospel of our Lord Jesus Christ; that so God, over all,
may have the glory and honour, to whom it belongs forevermore.

And now, dear Friends,
we have sometimes met together to discourse of trades and callings,
but more particularly of our own, which we are in, being tailors,
in which we have met with trials for many years,
though little of it has been declared by some of us,
knowing the arm of the Lord has supported us through all,
and given us a reward as we stood faithful to his requirings.
This is our desire for all that are convinced of the Lord`'s truth,
and know his heavenly way to walk in it;
and where anything appears to draw back or hinder,
though it be as the right hand or the right eye, yet if it offends, pull it out,
and cast it from you, and enjoy life, which is more than all.
And our desire for you all, is that you keep nothing back which God calls for;
and that you have not peace in your employments,
of which we have sometimes discoursed as superfluity, and things altogether needless,
which some of us for many years have left undone.
We wish it were so with all,
that there might be a clearness and an enlargement in the Lord`'s power,
and an increase of his love, which is much better than the increase of corn, or wine,
or oil.
And these things, Friends, we lay before you in the love of God,
being delivered from those burdens that many yet groan under, as lace, ribbons,
and needless buttons, altogether useless; and such like things,
which the light does not justify,
but are out of that in which the true fellowship stands.
As for answering the world in making their clothes,
we leave it to the witness of God in you all,
and as much as in you lies induce them to moderation; and as for Friends,
we hope that they will not desire, nor wear anything inconvenient,
and therefore need say nothing more about it:
believing the Lord will so open their understandings,
as that they will preach to the world in all things,
and adorn themselves as becomes the Gospel; which is the power of God,
by which we are called, and the way in which we are to walk;
while we are in these earthly tabernacles;
that so our lights may shine forth to the world, and they seeing our good works,
may glorify our Father which is in heaven, and that many may say, '`Come,
and let us go up to the mountain of the Lord, and to the house of the God of Jacob:
and he will teach us of his ways,
and we will walk in his paths.`' This is what our very souls travail for to God,
that every one convinced of the Lord`'s heavenly truth may enjoy it fully,
and that nothing may be lacking; and for this cause is this written,
in dear and tender love to you all, not as exercising lordship over God`'s heritage,
nor with reflection upon any man`'s person; nor for disputation,
nor leading into parties, or gratifying any narrow private judgment;
but for the honour of truth, and the glory of God, which is our whole aim,
the Lord knows.
So in the blessed unchangeable truth of God, we salute you all, dear brethren,
and in which we remain in love unfeigned,

[.signed-section-closing]
Your dear friends and brethren,

[.signed-section-signature]
Gilbert Latey, John Bowlover, William Walker, Thos.
Taunton, Edw.
Eldershaw, William Taylby, William Tillit, Jolm Pearce, William Brown, Henry Day,
Degory Marshal, Jolm Thorpe.

--

I now come to give some account of Gilbert`'s service in attending King Charles,
which he did several times; but my intention being brevity,
I shall give but one relation out of them all, it being thus: In the year 1683,
Friends at Norwich were under severe sufferings and close confinement,
for meeting to worship the Lord,
according as in conscience they were persuaded was their duty; sixty-three persons,
both men and women being imprisoned, ten of them in a low dungeon,
twenty-nine steps under ground, and several in the hole among the felons.
The cruelty of their sufferings cried aloud, and the severity they underwent,
through the rage of the sheriff and jailer, not being warrantable according to law,
stirred up Friends the more to have those sufferings laid before the king.

In order to this, they drew up the case;
and Gilbert with our ancient and honourable Friend, George Whitehead,
whom he truly loved, and ever had a more than ordinary esteem for,
were appointed to deliver it to the king; they being known to him,
both having attended him before.
The king being at Windsor, and the council to meet at Hampton-court,
about the middle of the second month, George and Gilbert went the evening before,
intending for Kingston; but the tide being spent, and the wind strong against them,
they could reach no farther than Wandsworth.
Next morning, though wet, they went on foot to Kingston,
where making but a very little stay at Ann Fielder`'s, who was Gilbert`'s mother-in-law,
they proceeded towards Hampton-court;
and having gone something more than half way up the park,
saw a concourse of people near the canal, and drawing a little nearer,
perceived the king was there.
Being come pretty near the king, some of his nobles took notice of them, and said,
the Quakers were coming towards his majesty; the king then looking towards the Friends,
said he thought he knew them; upon which they spoke,
and desired he would be pleased to hear them a few words,
they being come on purpose from London to attend him.

Upon this the king was pleased to make a little stop,
and George delivered to him the case of our Friends,
and laid before him the severities and hardships they underwent,
and that it was contrary to law.
The king was pleased to say he would search into the matter; adding,
"`I will not have them overcharged contrary to law by any means,
but will have my laws observed;`" and after his thus speaking, was very pleasant,
and asked the Friends several questions, as why they could not as well say, Aye and No,
as Yea and Nay?
To which they answered, that it was equal to our Friends, either to say Aye or No,
or Yea or Nay, that which was most proper they could make use of "`But,`" said the king,
"`you will say Thee and Thou; what is your reason for that?`"
To which Gilbert made answer, "`The same reason as the apostle Paul,
when speaking to King Agrippa, he says, '`I think myself happy, King Agrippa,
that I shall answer for myself before thee,
especially because I know thou art expert in all customs,`' etc.
Also, '`King Agrippa, believest thou the prophets?
And, would to God not only thou, but also all that hear me this day,
were both almost and altogether such as I am,
except these bonds.`'`" Upon this the king made a little pause,
and seemed to question whether these passages were truly translated, yet said,
the translators might have translated You, as well as Thou, from the Greek;
upon which George answered, "`Then the translators were as simple as we Quakers.`"
The king replied, "`But you will not pull off your hats,
and what have you to say for that?`"
To which Gilbert answered, "`If to any mortal, then to the king in the first place;
but it is a matter of conscience,
and we only do it when we approach the Lord in prayer.`"
"`But,`" said the king, "`for all this,
there are some among you that have not done well:`" to which Gilbert answered,
"`They have no more pleased us than the king:`" whereupon some of the nobles said,
"`May it please your majesty,
your majesty says some among these people have not done well;
must they be charged with that?
It may be possible that some of your majesty`'s own servants may not have done well,
shall we therefore be blamed for that?`"
"`No,`" said the king, "`God forbid;`" upon this some of the nobles replied, "`Pray,
your majesty, hear these men, for they speak well,
and they look well on your majesty;`" said the king, "`I protest so they do,
I admire to see such wise men Quakers.`"
Then Gilbert asked if they might speak freely,
for that they were in great hazard in approaching the king`'s
presence upon which the king stretched out his hand,
and said, "`Let no man molest or meddle with them,
but let them come to me when they have occasion:`" upon which Gilbert replied,
"`We thank God we have had the favour of seeing the king`'s face this day,
and wish the king health, prosperity, and length of days;
and all you nobles that attend the king this day,
the Lord reward you for your moderation towards us.`"
George Whitehead again entreated the king to remember
the prisoners`' case presented to him,
which he promised he would;
upon which the king and nobles that attended him withdrew to the council;
and the Friends returned, after the council was over, to London.

The court sessions coming on soon after, the judges,
when they came on the bench at Norwich, were very moderate;
and when the Friends were brought before them, made a motion,
that four or five of them should engage for the whole to appear at next court sessions,
when called; which being accepted, they all had their liberty;
and the women Friends were wholly cleared,
and no fees laid to be paid by either the men or women,
all which proceeded from the attending the king,
and his clemency to his suffering subjects.

In or about the year 1671, Gilbert having occasion in the way of his trade,
which lay much among great people, to wait on the lady Sawkell;
after having dispatched the business he went about.
Sir William Sawkell, the lady`'s husband,
who then had a command under the earl of Oxford, in his regiment of horse,
came into the room, and having, as well as his lady, a kind respect for Gilbert,
was often familiar with him.
Sir William asked him, What meeting he went to?
to which he answered, "`Sometimes to one meeting,
and sometimes to another:`" "`The reason,`" said Sir William, "`why I ask is,
because I have had orders to go and break up a meeting of your people at Hammersmith,
which I have deferred executing, and now I have a fresh command laid on me,
and I cannot avoid it, but must go there on Sunday next,
and therefore I speak in kindness to you, if you use at any time to go there,
that you refrain coming that day;
for I receive my command from so high a hand that I dare not omit executing thereof.`"
Upon this discourse it was immediately laid on Gilbert,
that he must be at Hammersmith at the same time Sir
William had desired he would avoid coming,
and accordingly he told him so before they parted.
Not consulting with flesh and blood, he offered up himself;
and went accordingly to the meeting, the Lord`'s good presence accompanied him,
and gave him the word of life to declare,
in the authority of which he stood up and delivered
that which was upon his heart towards the people,
who were assembled in the meeting.

While he was thus preaching, the troopers came into the meeting,
and stood for some time to hear the truth declared;
but one being more rude than the others, said, "`This man will never have done,
let us pull him down,`" and accordingly laid hands on him; after which Gilbert asked him.
Who commanded them?
to which they replied, "`Sir William Sawkell.`"
Then said Gilbert, "`Let your officer know I am here,
and my name is Gilbert Latey;`" which when Sir William heard, he came in trembling;
and at last said, "`Latey, did I not tell you that I was commanded to be here today?`"
to which Gilbert replied, "`You did,
but did I not also tell you I was commanded by one Greater than you are,
to be here also?`"
Upon this, said Sir William, "`Go, get about your business,
and I will take care concerning the rest here met;`" upon which Gilbert said,
"`If you have any respect for me, then discharge all the rest,
and let me be your prisoner:`" so after some time the Friends were set at liberty,
and Gilbert taken and carried before the lord Mordaunt and Sir James Smith,
who were met by appointment, as was supposed, to attend to this matter.
When Gilbert was brought before them, the troopers were called as evidence against him;
and Gilbert made his defence in such manner that
his words seemed to have place with them;
yet, notwithstanding, they fined him and the house,
and distrained on some Friends for the same,
among whom was William Simonds who had a horse taken from him.
But Gilbert was not easy that any Friends should suffer on his account;
and understanding they had got the horse and other goods,
which they kept still undisposed of,
he at last found means to be admitted to their presence,
and laid the cruelty of that severe law before them,
of making one to suffer for the offence of another; adding,
if he had transgressed any law,
the Lord had blessed him wherewith to enable them to take their course with him,
and therefore desired the Friends might not be made to suffer on his account,
or for anything by him said or done.
Having frequent opportunities to address himself to them,
and also the favour of some who were their equals, and acquaintance,
to speak to them on his and the Friends`' behalf, and the goods, though long detained,
not being sold, he at last so far prevailed,
that the lord Mordaunt gave him a warrant, that the horse and goods thus taken,
should be restored to the owners; and superseding the former warrant for distress,
empowered Gilbert and the Friends to take the horse
and other goods where they should find them.
Friends knowing where they were, went accordingly, and demanded them,
and had them restored, which was no small joy to Gilbert,
that the suffering designed on the Friends of that meeting,
was through the goodness of the Lord thus prevented.

The Lord`'s power sustained and upheld his people,
by which Gilbert was carried on in his testimony;
and notwithstanding exercises were permitted, and indeed abounded,
yet the love of God did much more abound, and he, with what he had, was preserved;
no Friend, as ever I heard of, suffering any more distress upon his account.
For being a man of ability, the justices and informers were willing,
when they had opportunity, to fix what they were permitted to take,
either by law or otherwise, upon him; by reason of which,
there were at one time warrants against him for several hundred pounds;
but the Lord being good to him, even as to his servant of old,
made the enemies ready to say as their master did, "`Does he serve God for nought;
has he not set a hedge about him, and all that he has?`"
For, notwithstanding their contrivance and subtlety,
the Lord preserved both him and what he had,
that the destroyers`' power was always in measure limited; for which, to the great God,
belongs the praise.

In the year 1679, he took another journey to visit his native place,
in the county of Cornwall; passing through Reading, and visiting some Friends there,
he proceeded on to the north part of the county,
to wait on a family which in those days bore great sway in the county of Berks,
and had been kind to Friends.
After having received a friendly and kind entertainment from them, he went to Bath,
and Bristol, visiting Friends as he had opportunity; and through part of Somersetshire,
and the north part of Devonshire, till he came to Falmouth in Cornwall.
Doctor Lamplugh, the then bishop of Exeter,
had done him several favours in respect to Friends under sufferings in his diocese;
which made Gilbert the more solicitous to inquire, as he passed through the same,
how things generally were with Friends up and down that diocese,
as also in the courts then kept by and under the said bishop;
and finding his moderation and kindness to have been
extended in a general manner to Friends,
Gilbert, according to his usual custom,
on his return waited on the bishop at his palace in Exeter,
to acknowledge the favours he had so largely extended to Friends.
The bishop received him with a great deal of kindness, taking him in his arms,
and expressed his benediction; after which he led him into a private room, and said,
"`All must not know how well you and I love one another;`" and then asked Gilbert,
what wine he should give him; to which he replied,
he had given him that which was better.
"`Pray,`" said the bishop, "`what mean you by that?`"
said Gilbert, "`You have given me your love, which is better than wine.`"
"`Then,`" said the bishop, "`if so, pray sit down by me; and if it may be no offence,
how far have you been, or are going, in these parts?`"
To which Gilbert answered how far he had been, and told him of the inquiry he had made,
concerning the moderation both of him and his officers, to Friends.
"`Well,`" said the bishop, "`and I am sure you will not flatter any body,
and therefore tell me what name I have where you have been.`"
To which Gilbert replied, that he had no tidings to give but what was well;
upon which the bishop thanked him, both for his inquiry and report.
Gilbert again acknowledged his kindness and favours,
and after some time they took leave of each other.
Having at all times easy access to him,
and also the favour at any time when there might be occasion, to write to him:
in the year 1683 he wrote to the bishop, and received the following answer:

[.embedded-content-document.letter]
--

[.salutation]
Mr. Latey,

I had acknowledged the receipt of your civil letter before now,
but that I stayed till our court sessions were over,
that I might see what proceedings were made against any of your persuasion;
and I can hear of none.
I find no process of late against any of them in any of my courts,
for I have examined my officers about it.
What the justices of peace have done in their Monthly Meetings I know not; but sure I am,
that such as live quiet and peaceable in the land, by any order from me,
are no way disturbed;
and I believe the justices are gentle enough to such as do not affront them.
I never was, nor will be for persecution, but shall endeavour that by any amicable way,
such as have erred may be brought into the way of truth,
and that we may all enjoy one another in heaven.
I am now somewhat indisposed: writing is irksome to me.
God Almighty bless you;

[.signed-section-closing]
I am your truly loving friend,

[.signed-section-signature]
Thomas, Exon.

[.signed-section-context-close]
Exeter, March the 24th, 1683-4.

--

Soon after King James came to the crown,
Gilbert was one who presented the king with a list of 1500 Friends,
prisoners for conscience-sake, about 800 of whom being estreated,
and writs nigh ready to go forth for seizing their estates for twenty pounds per month,
Gilbert, with our honourable elder George Whitehead,
took great care and unwearied pains to procure a stop to be put to these violent prosecutions,
and obtained, by the king`'s commission,
the following order from the then lord Treasurer:

[.embedded-content-document.letter]
--

After my hearty commendations,
these are to authorize and desire you to forbear making
forth any process against any the persons hereunto annexed,
each sheet being subscribed by myself;
the three first sheets having four columns of names, the fourth only two,
till the next term; and if any process is already made forth,
you are immediately to supersede the same; and for so doing this shall be your warrant.

[.signed-section-context-close]
Whitehall Treasury Chamber, the 4th of March, 1685, Rochester.

[.signed-section-context-close]
To my very loving friend, the Clerk of the Pipe.

--

After the aforesaid warrant,
an order was obtained to lay these cases before Sir Robert Sawyer, the attorney-general,
who after a considerable time and solicitation,
made his report to the lord Sunderland and earl of Middleton, then secretaries of state,
who transferred the report to the king in council,
where an order was obtained to refer the matter to the lord privy-seal,
and that a warrant might be passed in that office to the pipe-office,
showing that the king had pardoned the offences and relinquished the fines.
The time this matter took up in soliciting and attending was not a little,
nor the fatigue the Friends underwent small, as was well known to many;
and at last their health was so impaired,
that Gilbert was made willing to leave his wife and family,
being hardly able to get into the coach which was to take him into the country.
He had not been there above a week,
when a letter came from his dear companion George Whitehead,
informing of his being taken so ill, that he could not go out of his house;
and that Gilbert, if possible, must return, or else the great cause would be at a stand.
Gilbert knowing the concern to be of great weight,
breathed unto God for strength to enable him to go on with the service;
which desire was answered by the Lord, and his strength renewed so that he returned,
and again attended at the pipe-office, till the matter was accomplished;
and soon after Friends were discharged.

After this was effected.
Friends were not free from sufferings; for,
notwithstanding so great a number were thus discharged,
abundance were still continued in prison; some, for not coming to the public worship,
or as they called it, for not coming to church,
were taken up and imprisoned on the __writ de excommunicato capiendo,__^
footnote:[A writ ordering the imprisonment of an excommunicated
person until he or she submitted to the church.]
and others who in obedience to Christ`'s command,
could not in these perilous times forsake meeting often together,
to wait upon and worship him, according as they were persuaded was their duty,
in spirit and truth, were sorely persecuted, fined, and committed to prison,
under close durance, till they should pay the fines.
Among these were several scores in Newgate in the city of Bristol,
some of whom were merchants and dealers in the said city;
and many being under confinement in other parts of the nation;
Gilbert was one who attended the king with a petition on their behalf.
It had so good effect, as to obtain their liberty and relief,
as may be perceived by the following report from the attorney-general:

[.embedded-content-document.legal]
--

I have considered of this petition, and of the several cases annexed.
For those that are in prison for not coming to church, or upon _excommunicato capiendo,_
for the same, I can discharge upon a former warrant directed to me,
which I have offered to do;
but the far greater number of those in the schedule are imprisoned until they
pay their fines set upon them for unlawful conventicles within the city of Bristol,
to which city the fines are granted by their charter; and I do find that the sheriffs,
to whom those fines are allotted, have acquitted their fines under their hands;
so that I conceive they may be discharged without further warrant from his majesty;
which I shall take care of; and also as to those fined in Southwark,
annexed to this schedule, or any others which are fined for being at conventicles,
whose fines are not pardoned.
But if his majesty, of special grace, be pleased to discharge them,
the easiest way to them will be by a warrant under his majesty`'s signet,
to acknowledge satisfaction, and thereupon to set them at liberty; and by like warrant,
the persons imprisoned upon an excommunication, may be set at liberty.

[.signed-section-signature]
Robert Sawyer.

[.signed-section-context-close]
May the 5th, 1686.

--

Gilbert again attended the king,
to lay before him the hardships our Friends underwent by mercenary informers;
and also gave him an account of Friends having been for
some years kept out of their meeting-place at the Savoy,
in the Strand, of which the soldiers kept possession and made it their guard-house;
and that in the same manner they kept Friends out
of their meeting-place at the Park in Southwark,
who for a considerable time met without doors,
the soldiers having converted one part of the meeting-house into a guard-room,
and fitted the other part to read mass in.
As to the matter which related to some of the chief informers that harassed our meetings,
and made great spoil of Friends`' goods, as mentioned in the petition,
a warrant was thereupon granted by the king, for the examination thereof;
a copy whereof follows:

[.embedded-content-document.legal]
--

Whereas several persons called Quakers, have exhibited a petition to his majesty,
complaining of several misdemeanours and irregularities of several informers;
and his majesty having been pleased to refer the examination thereof to us,
by warrant from the right honourable the earl of Middleton,
one of his majesty`'s principal secretaries of state,
we do appoint to consider of the same on Friday,
being the fourth day of June next ensuing, at four of the clock in the afternoon,
at Mr. Graham`'s chamber, in Clifford`'s Inn; and we desire you, the persons undernamed,
to be present then, in order to our proceeding in the said affair.

[.signed-section-closing]
Given under our hands, the last day of May, 1686.

[.signed-section-signature]
Richard Graham, per Burton.

[.signed-section-context-close]
To Jeffery Nightingale, Esq.
Peter Lugg, Esq.
Capt.
John Hilton.

--

Friends also appearing, made good their allegations and charges,
so that the informers received a just rebuke,
and met with so much discouragement from making further prosecution,
that this proved in great measure, a fatal stroke to those mercenary men,
who had made their boasts of what they would do to enrich themselves;
and in order thereto,
had set their agents in many parts to ruin the king`'s peaceable subjects.
But their hands were now very much weakened, and their designs broken by the Lord,
who soon after gave rest and peace to his church and people,
and restored to them their meeting-houses,
and the quiet enjoyment of their peaceable meeting together.

In the year 1688, Gilbert and two Friends, namely George Whitehead and William Penn,
meeting at White-hall,
they asked him if he would go along with them to wait upon the king.
He made some little pause before he gave his answer, having nothing in his mind to say,
or to attend the king for; and as he thus stood silent,
it opened in his heart what he should say to the king, whereupon he told the Friends,
he was ready to go with them.
Accordingly they went, and had admittance to the king`'s presence,
there being only one person present besides the king and the Friends.
George Whitehead and William Penn having spoken what they had to say,
the king was pleased to ask Gilbert whether he had not something to say; upon which,
in a great deal of humility, he spoke as follows: "`The mercy, favour,
and kindness which the king has extended to us as a people,
in the time of our exercise and sore distress, we humbly acknowledge;
and I truly desire that God may show the king mercy and
favour in the time of his trouble and sore distress.`"
To which the king replied, "`I thank you;`" and so they parted.

What was then spoken by Gilbert, lived with the king; and a considerable time after,
when in Ireland, he desired a Friend to remember him to Gilbert and "`Tell him,
the words he spoke to me I shall never forget; adding, that one part of them was come,
and he prayed to God the other might also come to pass.`"
Gilbert desired the Friend, when he returned again to Ireland,
if he had opportunity to see King James,
to let him know that the second part of what he had said, in relation to the king,
was also in great measure come to pass, and that the Lord had given him his life.

Soon after the coming in of King William,
the benefits resulting from the toleration allowed in the late reign,
made some think that it would be of great service,
if what was granted then by a dispensing power, might now, in this happy reign,
be established by a legal act of parliament;
and King William having a desire to make his subjects easy,
the promoting of this good work was acceptable to him.
A bill of that kind was proposed to the parliament,
and order given for the bringing it in, which accordingly was passed, under the title of,
"`An Act for exempting their Majesties`' Protestant Subjects,
dissenting from the church of England,
from the penalties of certain Laws,`" (being about thirteen in number;) and it was enacted,
"`That all Protestant dissenting Subjects should take the
oaths mentioned in a Statute made in that parliament,
and should make and subscribe the Declaration mentioned in a Statute
made in the thirtieth year of King Charles II;
which oaths and declaration the justices of peace
at the General Sessions were required to tender.`"

Upon the reading of this bill in the House,
Friends understanding the tenor of it to bind all to take the oaths aforesaid,
and as they for conscience sake could not swear in any case,
they solicited the parliament for a clause to make them
alike easy with the rest of the king`'s Protestant subjects.
Gilbert was one, with several others, appointed to attend this service,
and their labours were blessed with success.
A clause was prepared and received by the House; which is as follows:

Whereas there are certain other persons, dissenters from the church of England,
who scruple the taking of any oath; be it enacted by the authority aforesaid,
that every such person shall make and subscribe the aforesaid Declaration,
and also this Declaration of Fidelity,
following.`"--Which may be seen at large in the act passed in the mouth called May,
1689.^
footnote:[These include a solemn declaration of the subject
to be true and faithful to King William and Queen Mary,
a renunciation and abhorrence of the doctrine of the See of Rome,
that princes excommunicated and deprived by the pope or his officers,
may be lawfully deposed and murdered by their subjects;
and of the supremacy and jurisdiction of the pope in matters civil or ecclesiastical,
within the realm.]
Subscription was also required to a profession of Christian belief,
according to the words therein contained.^
footnote:[This profession of Christian belief, was drawn up by Friends,
and presented to the committee of parliament as a substitute for the one in the bill,
which contained some expressions not entirely agreeable to the Society.
The committee accepted the proposal, and it passed the House as follows, viz "`I, A. B.,
profess faith in God the Father, and in Jesus Christ his eternal Son, the true God,
and in the Holy Spirit one God blessed forevermore,
and do acknowledge the Holy Scriptures of the Old and New Testament,
to be given by divine inspiration.`"]

In the year 1694, being the fourth of the reign of King William and Queen Mary,
Gilbert attended the king at Kensington, with the following petition,
which had so good effect, that one hundred Friends were discharged.

[.embedded-content-document.address]
--

[.letter-heading]
To the King.

The case and request of the people called Quakers, in behalf of many of them,
who are present sufferers for conscience sake, humbly presented:

[.offset]
Showing:

That as the God of all our mercies has preserved us,
a peaceable and quiet people in the land,
according to our Christian principle and profession,
under the various revolutions of government,
so we humbly hope and resolve by his divine assistance, ever to continue;
being also heartily thankful for the several kindnesses
and compassions received from the government,
especially for the present liberty we now by law enjoy, in point of religious worship.
Yet forasmuch as many of the said people are continued under deep
sufferings in their persons and estates by tedious imprisonments,
seizures, and sequestrations; several also of late have died in prisons,
and many more +++[+++are]
under prosecution, and liable so to suffer in England and Wales,
tending to the ruin of many families; for these causes of conscience:
chiefly on contempts (as adjudged) for not answering on oath in cases of tithes,
when sued in the Exchequer, and also for not answering upon oath,
when prosecuted in the Ecclesiastical Courts for tithes, church rates,
etc. whereupon they proceed to excommunication, and by _signifcavits,_
procure__ writs de excommunicato capiendo,__
and sometimes justices`' warrants to imprisonment.

We therefore humbly remind the king of the great severities
and prosecutions formerly inflicted on us,
which were sometimes abated and respited,
when it pleased God to move the hearts of the kings and
governments to show compassion and favour to us,
whereof these are some instances:

[.numbered-group]
====

[.numbered]
_First._ By King Charles II. his proclamation of grace in 1661,
whereby many of our Friends were released out of prisons.

[.numbered]
_Secondly._ By his letters patent, or pardon in 1672,
pursuant to his declarations of indulgence to tender consciences in the same year.

[.numbered]
_Thirdly._ By an act of parliament, the 25th of Charles II., chap.
5, entitled, '`An Act for the King`'s Majesty`'s most gracious, general,
and free pardon,`' pardoning contempts, etc. against the king;
whereby many also of the said people were discharged and released out of prisons.

[.numbered]
_Fourthly._ Also by King James II., many were released out of prisons,
and relieved by several commissions, and two general proclamation pardons,
the one in 1685, and the other in 1688.

[.numbered]
_Fifthly._ And also by an act of '`gracious, general,
and free pardon,`' in the second year of King William and Queen Mary,
several were discharged from contempts and imprisonments.

====

These foregoing noted precedents of royal favour and compassion to the oppressed,
and the present confinements and hardships of many innocent persons, tenderly considered;

We, the said people, humbly request,
that the king would be pleased to extend his favour
and compassion towards the said sufferers,
for their lawful ease and relief from the present confinements,
as in his wisdom and clemency shall seem most fitting and convenient.

[.signed-section-context-close]
Signed in behalf of the said people and sufferers,
and delivered to the king at Kensington, in the second month, called April, 1695

--

In consequence of this application, about one hundred Friends who were prisoners,
were soon after discharged by an act of indemnity,
for which our acknowledgments are due both to God and the government.
After all the waiting and solicitations, although ease was obtained for some,
others were under severe sufferings,
which often arose by Chancery and Exchequer proceedings, the inability of proving wills,
and other matters, where an oath was required,
which Friends for conscience sake could not take.
The weight of these sufferings came on several faithful Friends, as also on Gilbert,
which they communicated to the Meeting for Sufferings,
who encouraged their soliciting King William,
whose family had relieved a people called Mennonites in the case of oaths, in Holland,
and part of Germany.
These faithful Friends feeling the Lord`'s power to attend them,
did accordingly again in the same year approach the king`'s presence,
and acquainted him of the sufferings many Friends lay under,
by reason they could not swear in any case;
and how helpful his predecessors had been to a people in Holland,
who were also conscientious in that respect,
and humbly desired if it was the king`'s pleasure,
that Friends might partake of his royal favour in that case;
to whom his gracious answer was.
That he was for it.
Upon this Friends requested,
that the king would favourably recommend this case to some leading members of parliament,
when we should have opportunity to move the parliament therein,
which he promised he would, and did accordingly.

This kind reception of the king encouraged Friends
to solicit some of the ministers of state also;
and finding the Lord had mollified their hearts towards them,
were willing also to attend some of the leading members of the House of Commons,
whose hearts the Lord likewise had inclined to moderation,
and the Friends that were given up to this service,
found the presence of the Lord to be with them,
and attend them in this great undertaking;
and it so prevailed on some eminent peers and commoners,
that Friends were invited to prefer their petition for relief in the case of oaths.
It was accordingly presented to the Commons then assembled in parliament,
which they received, read, and ordered a bill to be brought in,
according to the prayer of the petition, which was done;
and being read a first and second time, was committed.
The House divided upon the bill, every reading:
however the Friends who were given up to attend this service,
being supported and carried above the discouragements they met with,
persisted in faith and patience, encouraging one another,
and sometimes speaking each to the other, that the Lord`'s peace attended them:
And his power was manifestly seen; insomuch, that some who came out,
upon the House being divided on the bill, in order to poll, said,
they could not but stand in admiration to see what a number came out for the bill,
who in other cases were so opposite to anything that might give ease to the dissenters.
One in particular, the son of a great duke, came and told Gilbert,
he could not but admire to see so great a number
of those who opposed the moderate party in the House,
come out and poll with them for the bill.
So great was the Lord`'s power,
that it prevailed upon many that were not before for Friends`' ease,
but their hearts being softened, and in measure changed,
they were made helpful to carry on this great work.

Much opposition however was made by some members of the House,
who used indefatigable endeavours to prevail with all they could to withstand Friends;
and one in particular, who was a very leading man, on the last reading of the bill,
came out of the House a little before it was to come on;
and having a prevailing power over many,
and a great interest in general with most of the leading members,
went into the Court of Requests, and places adjacent,
to gather up all the strength he could to carry into the House with him.
In the mean time, the House, having read and gone through the bill,
the question being put, a poll was agreed;
so that when this great man and the company he had got together, came to the door,
and were ready to enter into the House, the door was shut against them all,
and the lobby ordered to be cleared;
and both he and his company were eager to go out with the rest.
The Lord knows the sighs and prayers that were put up to him that day for his people;
and it was in measure a strength and a confirmation to Gilbert and others,
to see the adversaries of Friends thus disappointed; all which being the Lord`'s doing,
was marvellous in the eyes of his servants, who attended there and saw the same,
ascribing the praise to him alone.

The bill being then ordered to be carried before the Lord`'s,
the Friends concerned went on in faith,
and gave their attendance on the members of that house,
and laid the reasonableness of the bill before many of them;
also before several of the bishops;
and the good presence of the Lord was still felt to go with them,
and make way in the hearts of these great ones, and by his secret and invisible hand,
wrought for the carrying on what had been thus far prosperously advanced.
And though the labour of Gilbert and his companions, in their attendance,
was some months, from the time they went to the king,
until it was quite passed the House of Lord`'s, the faith of some never failed,
nor were they dismayed, but felt that which supported and bore them up under all,
and crowned their labours by obtaining ease for the Lord`'s people;
whose prayers were put up to the great God for his blessing to attend those his servants,
in getting accomplished what thus happily was begun.
And, rejoicing together, +++[+++they had to]
bless the name of Him who lives forever and evermore.

I shall here add one account more,
it being an application drawn up and signed by Friends, and delivered to King William,
by Gilbert and some Friends appointed; and is as follows:

[.embedded-content-document.address]
--

[.letter-heading]
To King William the Third, over England, etc.

The grateful acknowledgment of the people commonly called Quakers, humbly presented.

[.salutation]
May it please the King,

Seeing the most high God, who rules in the kingdoms of men,
and appoints over them whomsoever he will, has by his overruling power and providence,
placed you in dominion and dignity over these realms,
and by his divine favour has signally preserved and
delivered you from many great and imminent dangers,
and graciously turned the calamity of war into the desired mercy of peace;
we heartily wish that we and all others concerned, may be truly sensible,
and humbly thankful to Almighty God for the same,
that the peace may be a lasting and perpetual blessing.
And now, O king, the God of peace having returned you in safety,
it is a cause of joy to them that fear him, to hear your good and seasonable resolution,
effectually to discourage profaneness and immorality;
righteousness being that which exalts a nation;
and as the king has been tenderly inclined to give ease and liberty
of conscience to his subjects of differing persuasions,
of whose favour we have largely partaken;
so we esteem it our duty gratefully to commemorate and acknowledge the same,
earnestly beseeching Almighty God to assist the king
to prosecute all these his just and good intentions,
that his days may be happy and peaceable; and hereafter,
he may partake of a lasting crown that will never fade away.

[.signed-section-context-close]
Signed +++[+++by a great many]
in behalf of the said people--London, the 7th of the 11th month, called January, 1697.

--

Upon delivering the aforesaid paper at Kensington, the 1st of the twelfth month, 1697-8,
Gilbert addressed him as follows:

[.small-break]
'''

"`May it please the King,
The favours received from the king can never be sufficiently acknowledged;
but this we can truly say, we have prayed to Almighty God to bless and preserve you;
and now being returned again in peace and safety, we rejoice to see the king`'s face,
for we wish well to him,
and that the Lord may bless and preserve him to the end of his days;
and we are glad of this opportunity to acknowledge the favours and kindness,
which we have received from you, which have been many:
the Lord reward you for them all!`"
The king replied, "`I thank you, and I desire the continuance of your prayers for me.

[.asterism]
'''

[.embedded-content-document.testimony]
--

[.blurb]
=== A Testimony of Gilbert Latey, Which He Desired Might Be Communicated to the Women`'s Meeting in London.

In early days, about three or four years after the settlement of the men`'s meeting,
which was in an upper room at the then Bull and Mouth meeting-house, near Aldersgate,
London; Gerard Roberts, Amor Stoddard, John Osgood, Richard Davis, and others,
being about fifteen or more,
being met about the concerns of the poor fatherless and widows among us,
as it had been advised by our elder brethren,
we found it was our place to look into the necessities of poor Friends,
and supply their needs: and a care came upon us how this should be carried on.
We could truly say, the Lord`'s presence and power was livingly felt among us,
whereby our hearts were opened,
and we enlightened to see that we needed help-mates for carrying on the service.
Upon which it opened in our hearts plainly,
that the women being added to us as help-mates,
would answer the service which was so needful,
and that we could no longer do without their help, care and assistance;
we believing it would lie much on them as their concern,
being satisfied they were fitted for the work,
and would be careful and vigilant therein.^
footnote:[This appears to have been the first attempt at
employing women Friends in the services of the Society,
and so beneficial were the results,
that it prepared the way for the establishment of Women`'s Meetings for Discipline;
the use of which has been confirmed by long experience.
The period to which Gilbert Latey alludes was about the year 1669.]
All the meeting, as one man, feeling the love of God to be shed abroad among us,
did in the openings of life agree,
that two of the meeting should go to Gerard Roberts`' house to acquaint
the ancient ministering Friends with what had opened in our hearts,
in relation to that service; there being then at Gerard Roberts`'s, George Fox,
Francis Howgill, Edward Burrough, Richard Hubberthorn, and it may be some more.
The matter being proposed to George Fox and the rest of the brethren,
they very well approved it,
and consented we might be joined together in the
work and service of the Lord among his people.
It was forthwith ordered that the names of the ancient women Friends,
from all parts of the city and suburbs, should be taken, which was done,
and some from every Quarter met, who readily associated;
and there was a heavenly union in our being thus joined together,
and the Lord was with us and among us, and continued his good presence,
both with them and us to this day.
And whereas some have gainsaid;
such consider not the work of God therein which was the ground and foundation
by which the men`'s and women`'s meetings were first gathered and confirmed,
and have been since preserved in that service.
The blessing of the Lord has attended, and does still attend them,
for the refreshing and comforting many a poor soul,
to whom God has in mercy ministered by them, to their great comfort and joy.

The Power that first gathered and settled us in this service is still the same,
and as it has hitherto done, will break down all that rise in opposition thereto,
and preserve them that have been faithful in this the Lord`'s business;
for he has blessed, and will bless all such who continue their obedience,
serving the Lord to the end.
Every one who has felt and tasted of his power, will have great satisfaction,
as well as myself,
who am a living witness of his heavenly appearance among us at the first;
and therefore I was willing to give this account and testimony,
to you the women Friends and all others, before I go hence, being now grown ancient,
and not likely to continue long;
but calling to mind the beginning and establishing of this meeting,
which many now know little of, I was the more induced to leave these few lines;
who am your ancient friend and truly loving brother,

[.signed-section-signature]
Gilbert Latey.

[.signed-section-context-close]
Hammersmith, the 22nd of the 6th mo., 1705.

--

[.embedded-content-document.epistle]
--

A Salutation of endeared love to the whole flock of God,
but in a more particular manner to the Friends and brethren
of the Monthly Meeting at the Savoy in Westminster;
whose prosperity, welfare, and perseverance in the work and service of the blessed truth,
whereunto the Lord has called you, I have ever desired,
that in it his heavenly power and life may be felt,
to preserve you all in love and unity, which is the bond of peace.
Dwell all in his pure fear, to act for his glory; and as all are kept and preserved here,
they will know their places in the body, bound up together in love,
where the elders will have a godly care for the younger,
and the younger be in subjection to their elders.
So will good order be kept, and heats be shut out from among you,
and mercy overshadow the judgment seat, where peace and good-will may he felt to abound,
in which the Lord`'s presence will preserve you all;
and this has been the breathing desire of your ancient friend and brother,

[.signed-section-signature]
Gilbert Latey.

[.signed-section-context-close]
Hammersmith, the 25th of the 6th mo., 1705.

--

[.asterism]
'''

Gilbert married Mary, the only daughter of John and Ann Feilder, of Kingston-upon-Thames,
in the county of Surrey, by whom he had eleven children,
of whom only two lived to the years of men and women.

Though he was long weak and feeble as to the outward, yet he was fresh, strong,
and living in his inward man; and in the latter end of the fifth month, 1705,
was at the meeting at Hammersmith.
A large meeting being then assembled, the Lord moved him to stand up,
and so supported him by his divine power,
as to enable him to sound forth the acceptable day of God,
and an invitation to all to come to Him, in and through the Lord Jesus Christ,
the alone mediator between God and man,
who is the way and only means to restore man again into the image and favour of God;
concerning which he there declared about an hour,
with a great deal of fervency and his customary zeal,
as if he had been under no infirmity of body,
even to the admiration of many of the hearers;
he being carried forth in a more than ordinary manner in this his last sermon.

Being resigned to the will of God,
he patiently waited on the Lord till he should be pleased to remove him,
and having lived to a good old age, being in the 79th year of his pilgrimage,
on the 15th of the ninth month, 1705, the Lord took him to himself, in great peace.

And now in conclusion, I may say of Gilbert,
that as he attended all the former kings and princes of this nation,
which were in his time, with most of the ministers of state in former reigns,
as well as many of the bishops; so likewise in the present queen`'s reign,
he did not fail, as occasion offered and his strength permitted,
to solicit the ease of the Lord`'s people; and having long served the families of some,
of the great persons in the nation, he had easy access,
they knowing that he came not for any worldly advantage to himself; some of them saying.
He comes not for anything we have, for he needs nothing of that.

In all these engagements he kept to and bore the cross of our Lord Jesus Christ,
by which he was crucified to the world;
and his great self-denial was taken notice of and beloved; insomuch,
that an eminent Friend and minister of Christ, in one of the former reigns,
being then in another nation,
having great interest among the men at court and attending there often,
meeting with a Friend one day, told him he had been at court, and that of all the men,
among Friends, that he ever knew or heard of,
he never followed a man that had a sweeter character than Gilbert Latey had at court.

It was his practice, in soliciting kings, princes and great men,
to keep to the anointing and love of God; and, as that gave utterance, to speak;
in which he oftentimes reached and had place in them;
and his solicitation was often answered, which made him say,
that as Friends feel and keep to this anointing in their solicitations,
they may expect a blessing, and therein be made serviceable to the Lord`'s people;
but if, on the contrary, any shall go in these services, in their own will,
wit and parts, they may miss the desired end, as some have done;
notwithstanding the children of this world are, as of old,
wiser in their generation than the children of light.
